import { useEffect, useRef, useState } from 'react'
import { ApiClientError, createIntentKey } from '../../lib/api/client'
import type { CollectionType } from '../../../packages/contracts/src'
import type { CreateInput, DetailView, ItemView, MetadataInput, PinInput } from './api'
import { collectionCopy as c } from './copy'
export interface VersionOption { id: string; assetId: string; title: string; label: string }
function asError(value: unknown) { return value instanceof ApiClientError ? value : new ApiClientError('Unable to save collection.', { code: 'UNKNOWN' }) }
function ErrorSummary({ error, validation, reload }: { error: ApiClientError | null; validation: string; reload?: () => void }) { return error || validation ? <div className="project-error" role="alert" tabIndex={-1}><p>{error?.message ?? validation}</p>{error?.details.map((value, index) => <p key={index}>{value.message}</p>)}{error?.requestId && <p>{c.requestId}: {error.requestId}</p>}{error && <p>{error.code === 'CONFLICT' ? c.conflict : c.failedWrite}</p>}{error && reload && <button type="button" onClick={reload}>{c.reload}</button>}</div> : null }
export function CollectionForm({ collection, versions, save, cancel, reload }: { collection?: DetailView; versions: VersionOption[]; save: (input: CreateInput | MetadataInput, key: string) => Promise<void>; cancel: () => void; reload?: () => Promise<DetailView> }) {
  const [name, setName] = useState(collection?.name ?? ''); const [description, setDescription] = useState(collection?.description ?? ''); const [type, setType] = useState<CollectionType>('DELIVERABLE'); const [pins, setPins] = useState<Record<string, string>>({}); const [expected, setExpected] = useState(collection?.updatedAt ?? ''); const [latest, setLatest] = useState<DetailView | null>(null); const [error, setError] = useState<ApiClientError | null>(null); const [validation, setValidation] = useState(''); const [saving, setSaving] = useState(false); const form = useRef<HTMLFormElement>(null); const busy = useRef(false); const intent = useRef<{ body: string; key: string } | null>(null)
  useEffect(() => { form.current?.querySelector<HTMLElement>('input')?.focus() }, [])
  async function submit() { if (busy.current) return; if (!name.trim() || name.trim().length > 200) { setValidation('Enter a collection name of 1–200 characters.'); form.current?.querySelector<HTMLElement>('input')?.focus(); return } const input: CreateInput | MetadataInput = collection ? { name: name.trim(), description: description.trim() || null, expectedUpdatedAt: expected } : { name: name.trim(), description: description.trim() || undefined, collectionType: type, items: Object.values(pins).filter(Boolean).map(assetVersionId => ({ assetVersionId })) }; const body = JSON.stringify(input); if (intent.current?.body !== body) intent.current = { body, key: createIntentKey() }; busy.current = true; setSaving(true); setError(null); setValidation(''); try { await save(input, intent.current.key) } catch (value) { setError(asError(value)); queueMicrotask(() => form.current?.querySelector<HTMLElement>('[role=alert]')?.focus()) } finally { busy.current = false; setSaving(false) } }
  async function readLatest() { if (!reload || busy.current) return; busy.current = true; setSaving(true); try { const value = await reload(); setLatest(value); setExpected(value.updatedAt); setError(null) } catch (value) { setError(asError(value)) } finally { busy.current = false; setSaving(false) } }
  return <form ref={form} className="asset-form" aria-label={collection ? c.edit : c.create} onSubmit={event => { event.preventDefault(); void submit() }}><h3>{collection ? c.edit : c.create}</h3><ErrorSummary error={error} validation={validation} reload={reload ? () => void readLatest() : undefined} />{latest && <p>Latest server metadata: {latest.name} · {latest.description ?? 'No description'}. Your draft is preserved; saving again uses the refreshed timestamp.</p>}<fieldset disabled={saving}><label>{c.name}<input value={name} maxLength={200} aria-invalid={Boolean(validation || error?.details.some(value => value.path === 'body.name'))} onChange={event => setName(event.target.value)} /></label><label>{c.description}<textarea value={description} onChange={event => setDescription(event.target.value)} /></label>{!collection && <><label>{c.type}<select value={type} onChange={event => { const value = event.target.value; if (Object.hasOwn(c.types, value)) setType(value as CollectionType) }}>{Object.entries(c.types).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><h4>Initial exact pins (optional)</h4><p>Choose at most one version of each asset. You can add and edit items in the draft.</p>{[...new Map(versions.map(version => [version.assetId, version.title])).entries()].map(([assetId, title]) => <label key={assetId}>{title}<select value={pins[assetId] ?? ''} onChange={event => setPins(previous => ({ ...previous, [assetId]: event.target.value }))}><option value="">Do not pin this asset</option>{versions.filter(version => version.assetId === assetId).map(version => <option key={version.id} value={version.id}>{version.label}</option>)}</select></label>)}</>}<div className="project-actions"><button>{saving ? c.saving : c.save}</button><button type="button" onClick={cancel}>{c.cancel}</button></div></fieldset></form>
}
export function RevisionForm({ revisions, selectedId, save, cancel }: { revisions: { id: string; revisionNumber: number; status: string }[]; selectedId: string; save: (body: { basedOnRevisionId: string; changeSummary: string }, key: string) => Promise<void>; cancel: () => void }) {
  const [base, setBase] = useState(selectedId); const [summary, setSummary] = useState(''); const [error, setError] = useState<ApiClientError | null>(null); const [validation, setValidation] = useState(''); const [saving, setSaving] = useState(false); const busy = useRef(false); const intent = useRef<{ body: string; key: string } | null>(null); const form = useRef<HTMLFormElement>(null)
  useEffect(() => { form.current?.querySelector<HTMLElement>('textarea')?.focus() }, [])
  async function submit() { if (busy.current) return; if (summary.trim().length < 3 || summary.trim().length > 1000 || !base) { setValidation('Choose a base revision and enter a change summary of 3–1000 characters.'); return } const body = { basedOnRevisionId: base, changeSummary: summary.trim() }; const fingerprint = JSON.stringify(body); if (intent.current?.body !== fingerprint) intent.current = { body: fingerprint, key: createIntentKey() }; busy.current = true; setSaving(true); setError(null); setValidation(''); try { await save(body, intent.current.key) } catch (value) { setError(asError(value)) } finally { busy.current = false; setSaving(false) } }
  return <form ref={form} className="asset-form" aria-label={c.revise} onSubmit={event => { event.preventDefault(); void submit() }}><h4>{c.revise}</h4><p>{c.revisionNote}</p><ErrorSummary error={error} validation={validation} /><fieldset disabled={saving}><label>{c.base}<select value={base} onChange={event => setBase(event.target.value)}>{revisions.map(value => <option key={value.id} value={value.id}>Revision {value.revisionNumber} · {value.status} · {value.id}</option>)}</select></label><label>{c.change}<textarea maxLength={1000} value={summary} onChange={event => setSummary(event.target.value)} /></label><div className="project-actions"><button>{saving ? c.saving : c.revise}</button><button type="button" onClick={cancel}>{c.cancel}</button></div></fieldset></form>
}
export function PinForm({ item, versions, count, save, cancel }: { item?: ItemView; versions: VersionOption[]; count: number; save: (input: PinInput | (Partial<PinInput> & { rationale?: string })) => Promise<void>; cancel: () => void }) {
  const [version, setVersion] = useState(item?.pinnedVersion.id ?? ''); const [role, setRole] = useState(item?.role ?? ''); const [note, setNote] = useState(item?.note ?? ''); const [position, setPosition] = useState(String(item?.position ?? count + 1)); const [rationale, setRationale] = useState(''); const [error, setError] = useState<ApiClientError | null>(null); const [validation, setValidation] = useState(''); const [saving, setSaving] = useState(false); const busy = useRef(false); const form = useRef<HTMLFormElement>(null)
  useEffect(() => { form.current?.querySelector<HTMLElement>('select')?.focus() }, [])
  const replacement = Boolean(item && version !== item.pinnedVersion.id)
  async function submit() { if (busy.current) return; const number = Number(position); if (!version || !Number.isInteger(number) || number < 1 || number > (item ? count : count + 1) || (replacement && rationale.trim().length < 5)) { setValidation('Choose an exact version and valid position. Replacements require a rationale of at least 5 characters.'); return } if (replacement && !window.confirm(c.confirmReplace)) return; busy.current = true; setSaving(true); setError(null); setValidation(''); try { await save({ assetVersionId: version, role: role.trim() || null, note: note.trim() || null, position: number, ...(replacement ? { rationale: rationale.trim() } : {}) }) } catch (value) { setError(asError(value)) } finally { busy.current = false; setSaving(false) } }
  return <form ref={form} className="asset-form" aria-label={item ? c.update : c.add} onSubmit={event => { event.preventDefault(); void submit() }}><h5>{item ? c.update : c.add}</h5>{item && <p>{c.replaceNote}</p>}<ErrorSummary error={error} validation={validation} /><fieldset disabled={saving}><label>{c.version}<select value={version} onChange={event => setVersion(event.target.value)}><option value="">Choose an exact version</option>{versions.filter(value => !item || value.assetId === item.pinnedVersion.assetId).map(value => <option key={value.id} value={value.id}>{value.label}</option>)}</select></label><label>{c.role}<input value={role} onChange={event => setRole(event.target.value)} /></label><label>{c.note}<textarea value={note} onChange={event => setNote(event.target.value)} /></label><label>{c.position}<input type="number" min={1} max={item ? count : count + 1} value={position} onChange={event => setPosition(event.target.value)} /></label>{replacement && <label>{c.replaceReason}<textarea value={rationale} onChange={event => setRationale(event.target.value)} /></label>}<div className="project-actions"><button>{saving ? c.saving : c.itemSave}</button><button type="button" onClick={cancel}>{c.cancel}</button></div></fieldset></form>
}
export function ReviewForm({ action, save, cancel }: { action: 'approve' | 'reject'; save: (body: { comment?: string; decision?: 'CHANGES_REQUESTED' | 'REJECTED' }) => Promise<void>; cancel: () => void }) {
  const [comment, setComment] = useState(''); const [decision, setDecision] = useState<'CHANGES_REQUESTED' | 'REJECTED'>('CHANGES_REQUESTED'); const [error, setError] = useState<ApiClientError | null>(null); const [validation, setValidation] = useState(''); const [saving, setSaving] = useState(false); const busy = useRef(false); const form = useRef<HTMLFormElement>(null)
  useEffect(() => { form.current?.querySelector<HTMLElement>('textarea')?.focus() }, [])
  async function submit() { if (busy.current) return; if (action === 'reject' && (comment.trim().length < 3 || comment.trim().length > 2000)) { setValidation('Review changes/rejection require a comment of 3–2000 characters.'); return } if (!window.confirm(action === 'approve' ? c.confirmApprove : c.confirmReject)) return; busy.current = true; setSaving(true); setError(null); setValidation(''); try { await save({ comment: comment.trim() || undefined, ...(action === 'reject' ? { decision } : {}) }) } catch (value) { setError(asError(value)) } finally { busy.current = false; setSaving(false) } }
  return <form ref={form} className="asset-form" aria-label={action === 'approve' ? c.approve : c.reject} onSubmit={event => { event.preventDefault(); void submit() }}><h4>{action === 'approve' ? c.approve : c.reject}</h4><p>{action === 'approve' ? c.confirmApprove : 'A rejected revision stays frozen. Continue work by creating a new draft revision.'}</p><ErrorSummary error={error} validation={validation} /><fieldset disabled={saving}>{action === 'reject' && <label>{c.decision}<select value={decision} onChange={event => setDecision(event.target.value === 'REJECTED' ? 'REJECTED' : 'CHANGES_REQUESTED')}><option value="CHANGES_REQUESTED">{c.changes}</option><option value="REJECTED">{c.rejected}</option></select></label>}<label>{c.comment}<textarea maxLength={2000} value={comment} onChange={event => setComment(event.target.value)} /></label><div className="project-actions"><button>{saving ? c.saving : c.reviewSave}</button><button type="button" onClick={cancel}>{c.cancel}</button></div></fieldset></form>
}
