import { useEffect, useMemo, useRef, useState } from 'react'
import { ApiClientError, type ApiClient } from '../../lib/api/client'
import { projectApi, type ProjectView } from '../projects/api'
import { assetApi } from '../assets/api'
import { collectionApi, type CollectionView, type DetailView } from './api'
import { CollectionForm, type VersionOption } from './CollectionForms'
import { CollectionWorkspace, Status } from './CollectionWorkspace'
import { collectionCopy as c } from './copy'
import { label } from '../references/display'
import '../assets/assets.css'
import './collections.css'
export function CollectionsPage({ client, projectId, collectionId, revisionId }: { client: ApiClient; projectId: string; collectionId?: string; revisionId?: string }) {
  const api = useMemo(() => collectionApi(client), [client]); const projects = useMemo(() => projectApi(client), [client]); const assets = useMemo(() => assetApi(client), [client]); const [project, setProject] = useState<ProjectView | null>(null); const [versions, setVersions] = useState<VersionOption[]>([]); const [contextError, setContextError] = useState<ApiClientError | null>(null); const [contextReady, setContextReady] = useState(false)
  const [items, setItems] = useState<CollectionView[]>([]); const [detail, setDetail] = useState<DetailView | null>(null); const [loading, setLoading] = useState(true); const [detailLoading, setDetailLoading] = useState(Boolean(collectionId)); const [moreLoading, setMoreLoading] = useState(false); const [cursor, setCursor] = useState<string | null>(null); const [error, setError] = useState<ApiClientError | null>(null); const [detailError, setDetailError] = useState<ApiClientError | null>(null); const [query, setQuery] = useState({ status: '', collectionType: '', includeArchived: false }); const [attempt, setAttempt] = useState(0); const [creating, setCreating] = useState(false); const [notice, setNotice] = useState(''); const generation = useRef(0); const paging = useRef(false)
  const filters = useMemo(() => ({ status: query.status || undefined, collectionType: query.collectionType || undefined, includeArchived: query.includeArchived }), [query])
  useEffect(() => { const controller = new AbortController(); async function load() { const [project, values] = await Promise.all([projects.get(projectId, controller.signal), (async () => { const values: VersionOption[] = []; let cursor: string | undefined; do { const result = await assets.list(projectId, { includeArchived: true, cursor }, controller.signal); const entries = await Promise.all(result.data.map(async asset => (await assets.versions(asset.id, controller.signal)).map(version => ({ id: version.id, assetId: asset.id, title: asset.title, label: `${asset.title} · Version ${version.versionNumber} · ${version.status} · ${version.id}` })))); values.push(...entries.flat()); cursor = result.page.nextCursor ?? undefined } while (cursor); return values })()]); if (!controller.signal.aborted) { setProject(project.data); setVersions(values); setContextError(null); setContextReady(true) } } void load().catch(value => { if (!controller.signal.aborted) { setContextError(asError(value)); setContextReady(false) } }); return () => controller.abort() }, [projects, assets, projectId, attempt])
  useEffect(() => { const controller = new AbortController(); const current = ++generation.current; paging.current = false
    // oxlint-disable-next-line react/set-state-in-effect -- Synchronize server filters and confirmed refreshes.
    setLoading(true); setError(null); setMoreLoading(false); setItems([]); setCursor(null)
    api.list(projectId, filters, controller.signal).then(result => { if (!controller.signal.aborted && generation.current === current) { setItems(result.data); setCursor(result.page.nextCursor); setLoading(false) } }).catch(value => { if (!controller.signal.aborted) { setError(asError(value)); setLoading(false) } }); return () => controller.abort()
  }, [api, projectId, filters, attempt])
  useEffect(() => { if (!collectionId) return; const controller = new AbortController()
    // oxlint-disable-next-line react/set-state-in-effect -- Reset detail when the collection route or confirmed state changes.
    setDetail(null); setDetailLoading(true); setDetailError(null); setCreating(false)
    Promise.all([api.get(collectionId, controller.signal), api.revisions(collectionId, controller.signal)]).then(([result, revisions]) => { if (result.data.projectId !== projectId) throw new ApiClientError('This collection belongs to another project.', { code: 'CROSS_PROJECT_REFERENCE' }); if (!controller.signal.aborted) { setDetail({ ...result.data, revisions }); setDetailLoading(false) } }).catch(value => { if (!controller.signal.aborted) { setDetailError(asError(value)); setDetailLoading(false) } }); return () => controller.abort()
  }, [api, collectionId, projectId, attempt])
  const canEdit = Boolean(contextReady && project && ['OWNER', 'EDITOR', 'REVIEWER'].includes(project.currentUserRole)); const canReview = Boolean(contextReady && project && ['OWNER', 'REVIEWER'].includes(project.currentUserRole))
  function changed(notice: string) { setNotice(notice); setAttempt(value => value + 1) }
  async function more() { if (!cursor || paging.current) return; paging.current = true; setMoreLoading(true); const current = generation.current; try { const result = await api.list(projectId, { ...filters, cursor }); if (current === generation.current) { setItems(previous => [...previous, ...result.data]); setCursor(result.page.nextCursor); setError(null) } } catch (value) { if (current === generation.current) setError(asError(value)) } finally { if (current === generation.current) { paging.current = false; setMoreLoading(false) } } }
  const retry = () => setAttempt(value => value + 1)
  return <><nav><a href={`#/projects/${projectId}`}>{c.overview}</a> · <a href={`#/projects/${projectId}/assets`}>View assets</a></nav><div className="projects-heading"><div><h2>{c.heading}</h2><p>{project?.name}</p></div>{canEdit && !collectionId && !creating && <button onClick={() => setCreating(true)}>{c.create}</button>}</div>{notice && <p role="status">{notice}</p>}{contextError && <ErrorMessage error={contextError} retry={retry} />}{project && !canEdit && !contextError && <p>{c.readOnly}</p>}
    {collectionId ? detailLoading ? <p role="status">{c.loading}</p> : detailError ? <ErrorMessage error={detailError} retry={retry} /> : detail && <CollectionWorkspace key={detail.id} api={api} collection={detail} projectId={projectId} revisionId={revisionId} versions={versions} canEdit={canEdit} canReview={canReview} changed={changed} /> : <>{creating && canEdit && <CollectionForm versions={versions} cancel={() => setCreating(false)} save={async (body, key) => { if ('collectionType' in body) { const result = await api.create(projectId, body, key); setCreating(false); changed(c.created); window.location.hash = `/projects/${projectId}/collections/${result.data.id}` } }} />}
    <div className="impact-filters"><label>{c.status}<select value={query.status} onChange={event => setQuery(previous => ({ ...previous, status: event.target.value }))}><option value="">{c.all}</option>{Object.entries(c.statuses).filter(([key]) => key !== 'REJECTED').map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><label>{c.type}<select value={query.collectionType} onChange={event => setQuery(previous => ({ ...previous, collectionType: event.target.value }))}><option value="">{c.all}</option>{Object.entries(c.types).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><label className="asset-checkbox"><input type="checkbox" checked={query.includeArchived} onChange={event => setQuery(previous => ({ ...previous, includeArchived: event.target.checked }))} />{c.archived}</label></div>
    {error && <ErrorMessage error={error} retry={retry} />}{loading ? <p role="status">{c.loading}</p> : <>{!error && !items.length && <p>{query.status || query.collectionType || query.includeArchived ? c.noResults : c.empty}</p>}<ul className="project-grid">{items.map(collection => <li key={collection.id} className="project-card"><Status value={collection.status} /><h3><a href={`#/projects/${projectId}/collections/${collection.id}`}>{collection.name}</a></h3><p>{label(c.types, collection.collectionType)}</p><p>Latest revision {collection.latestRevision.revisionNumber} · <Status value={collection.latestRevision.status} /></p><p>Pinned items: {collection.latestRevision.itemCount} · Items with newer versions: {collection.latestRevision.staleItemCount}</p><a href={`#/projects/${projectId}/collections/${collection.id}`}>Open collection</a></li>)}</ul>{cursor && <button disabled={moreLoading} onClick={() => void more()}>{moreLoading ? c.loading : c.more}</button>}</>}</>}
  </>
}
function asError(value: unknown) { return value instanceof ApiClientError ? value : new ApiClientError('Unable to load collections.', { code: 'UNKNOWN' }) }
function ErrorMessage({ error, retry }: { error: ApiClientError; retry: () => void }) { return <div className="project-error" role="alert"><p>{error.message}</p>{error.requestId && <p>{c.requestId}: {error.requestId}</p>}<button onClick={retry}>{c.retry}</button></div> }
