import { useEffect, useRef, useState } from 'react'
import { ApiClientError } from '../../lib/api/client'
import type { collectionApi, DetailView, RevisionView, ItemView } from './api'
import { CollectionForm, PinForm, RevisionForm, ReviewForm, type VersionOption } from './CollectionForms'
import { AssetMedia, AssetStatus } from '../assets/AssetMedia'
import { label } from '../references/display'
import { collectionCopy as c } from './copy'
export function CollectionWorkspace({ api, collection, projectId, revisionId, versions, canEdit, canReview, changed }: { api: ReturnType<typeof collectionApi>; collection: DetailView; projectId: string; revisionId?: string; versions: VersionOption[]; canEdit: boolean; canReview: boolean; changed: (notice: string) => void }) {
  const selectedId = revisionId ?? collection.latestRevision.id; const [revision, setRevision] = useState<RevisionView | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<ApiClientError | null>(null); const [writeFailed, setWriteFailed] = useState(false); const [attempt, setAttempt] = useState(0); const [mode, setMode] = useState<'metadata' | 'revision' | 'add' | 'item' | 'approve' | 'reject' | null>(null); const [selectedItem, setSelectedItem] = useState<ItemView | null>(null); const [busy, setBusy] = useState(false); const actionBusy = useRef(false); const heading = useRef<HTMLHeadingElement>(null)
  useEffect(() => { const controller = new AbortController()
    // oxlint-disable-next-line react/set-state-in-effect -- Synchronize the exact revision route with an API read.
    setRevision(null); setLoading(true); setError(null); setWriteFailed(false); setMode(null)
    api.revision(selectedId, controller.signal).then(result => { if (result.data.collectionId !== collection.id) throw new ApiClientError('This revision belongs to another collection.', { code: 'CROSS_PROJECT_REFERENCE' }); if (!controller.signal.aborted) { setRevision(result.data); setLoading(false); heading.current?.focus() } }).catch(value => { if (!controller.signal.aborted) { setError(asError(value)); setLoading(false) } }); return () => controller.abort()
  }, [api, selectedId, collection.id, attempt])
  const open = collection.revisions.find(value => ['DRAFT', 'IN_REVIEW'].includes(value.status)); const draft = revision?.status === 'DRAFT'
  async function action(run: () => Promise<unknown>, notice: string) { if (actionBusy.current) return; actionBusy.current = true; setBusy(true); setError(null); setWriteFailed(false); try { await run(); changed(notice) } catch (value) { setError(asError(value)); setWriteFailed(true) } finally { actionBusy.current = false; setBusy(false) } }
  function focus() { setMode(null); queueMicrotask(() => heading.current?.focus()) }
  return <article className="collection-workspace"><a href={`#/projects/${projectId}/collections`}>All collections</a><h2>{collection.name}</h2><p>{collection.description}</p><p>Collection: <Status value={collection.status} /> · {label(c.types, collection.collectionType)}</p><p>Approved revision ID: <code>{collection.approvedRevisionId ?? 'None'}</code></p>{canEdit && !mode && <div className="project-actions"><button disabled={busy} onClick={() => setMode('metadata')}>{c.edit}</button><button disabled={busy} onClick={() => { if (!collection.archivedAt && !window.confirm(c.confirmArchive)) return; void action(() => api.edit(collection.id, { archived: !collection.archivedAt, expectedUpdatedAt: collection.updatedAt }), collection.archivedAt ? 'Collection restored.' : 'Collection archived.') }}>{collection.archivedAt ? c.restore : c.archive}</button></div>}
    {mode === 'metadata' && <CollectionForm collection={collection} versions={versions} cancel={focus} reload={async () => (await api.get(collection.id)).data} save={async input => { if ('expectedUpdatedAt' in input) { await api.edit(collection.id, input); changed(c.metadataSaved) } }} />}
    <label>{c.revision}<select value={selectedId} disabled={busy || Boolean(mode)} onChange={event => { window.location.hash = `/projects/${projectId}/collections/${collection.id}/revisions/${event.target.value}` }}>{collection.revisions.map(value => <option value={value.id} key={value.id}>Revision {value.revisionNumber} · {label(c.statuses, value.status)} · {value.id}</option>)}</select></label>
    {loading ? <p role="status">Loading exact collection revision…</p> : revision && <><h3 ref={heading} tabIndex={-1}>Revision {revision.revisionNumber} · <Status value={revision.status} /></h3><p><code>{revision.id}</code></p><p>{revision.changeSummary}</p><dl className="home-metrics"><div><dt>Pinned items</dt><dd>{revision.itemCount}</dd></div><div><dt>Items with newer versions</dt><dd>{revision.staleItemCount}</dd></div></dl>
      {!draft && <p>{c.draftOnly}</p>}{open && canEdit && !draft && <p>{c.openRevision} <a href={`#/projects/${projectId}/collections/${collection.id}/revisions/${open.id}`}>Open revision {open.revisionNumber}</a></p>}
      {!mode && <div className="project-actions">{canEdit && !open && collection.revisions.every(value => Object.hasOwn(c.statuses, value.status)) && <button disabled={busy} onClick={() => setMode('revision')}>{c.revise}</button>}{canEdit && draft && <><button disabled={busy} onClick={() => setMode('add')}>{c.add}</button><button disabled={busy || revision.items.length === 0} onClick={() => void action(() => api.review(revision.id, 'submit-review'), 'Revision submitted for review.')}>{c.submit}</button></>}{canReview && revision.status === 'IN_REVIEW' && <><button disabled={busy} onClick={() => setMode('approve')}>{c.approve}</button><button disabled={busy} onClick={() => setMode('reject')}>{c.reject}</button></>}</div>}
      {mode === 'revision' && <RevisionForm revisions={collection.revisions} selectedId={revision.id} cancel={focus} save={async (body, key) => { const result = await api.revise(collection.id, body, key); window.location.hash = `/projects/${projectId}/collections/${collection.id}/revisions/${result.data.id}`; changed('Draft revision created with the original exact pins.') }} />}
      {mode === 'add' && <PinForm versions={versions.filter(value => !revision.items.some(item => item.pinnedVersion.assetId === value.assetId))} count={revision.items.length} cancel={focus} save={async body => { if (body.assetVersionId) { await api.add(revision.id, { ...body, assetVersionId: body.assetVersionId }); changed('Exact version added to the draft.') } }} />}
      {(mode === 'approve' || mode === 'reject') && <ReviewForm action={mode} cancel={focus} save={async body => { await api.review(revision.id, mode, body); changed(mode === 'approve' ? 'Revision approved. Pins are frozen.' : 'Review decision recorded. Create a new draft to continue.') }} />}
      {revision.items.length === 0 && <p>No pinned items in this revision.</p>}<ol className="collection-items">{revision.items.map(item => <li key={item.id} className="collection-item"><AssetMedia url={item.pinnedVersion.thumbnailUrl} title={item.pinnedVersion.assetTitle} /><div><h4>{item.position}. {item.pinnedVersion.assetTitle}</h4><p>{c.pinned}: Version {item.pinnedVersion.versionNumber} · <AssetStatus status={item.pinnedVersion.status} version /></p><p><code>{item.pinnedVersion.id}</code></p><p className={item.isStale ? 'collection-stale' : 'note'}>◷ {item.isStale ? c.stale : c.current}</p>{item.isStale && <><p>{c.latest}: Version {item.latestVersion.versionNumber} · <AssetStatus status={item.latestVersion.status} version /></p><p><code>{item.latestVersion.id}</code></p><p>{c.newer}: {item.newerVersionCount}</p><p>The exact pinned version is preserved. Replace it explicitly in a draft revision.</p></>}<p>{c.role}: {item.role ?? 'None'} · {c.note}: {item.note ?? 'None'}</p><a href={`#/projects/${projectId}/assets/${item.pinnedVersion.assetId}/versions/${item.pinnedVersion.id}`}>{c.inspect}</a>{canEdit && draft && !mode && <div className="project-actions"><button disabled={busy} onClick={() => { setSelectedItem(item); setMode('item') }}>{c.update}</button><button disabled={busy} onClick={() => { if (window.confirm(c.confirmRemove)) void action(() => api.remove(item.id), 'Draft item removed.') }}>{c.remove}</button></div>}{mode === 'item' && selectedItem?.id === item.id && <PinForm item={item} versions={versions} count={revision.items.length} cancel={focus} save={async body => { await api.item(item.id, body); changed('Draft item saved. The API confirmed its exact pin.') }} />}</div></li>)}</ol>
      <section className="home-panel"><h4>{c.approvalHistory}</h4>{revision.approvals.length === 0 && <p>{c.noApprovals}</p>}<ol>{revision.approvals.map(approval => <li key={approval.id}><strong>{label({ APPROVED: 'Approved', CHANGES_REQUESTED: 'Changes requested', REJECTED: 'Rejected' }, approval.decision)}</strong><p>{approval.comment ?? 'No comment'}</p><p>{approval.reviewedBy.displayName} · <time dateTime={approval.reviewedAt}>{new Date(approval.reviewedAt).toLocaleString()}</time></p><code>{approval.id}</code></li>)}</ol></section>
    </>}{error && <div className="project-error" role="alert"><p>{error.message}</p>{error.requestId && <p>{c.requestId}: {error.requestId}</p>}{writeFailed && <p>{c.failedWrite}</p>}<button disabled={busy} onClick={() => setAttempt(value => value + 1)}>{c.reload}</button></div>}
  </article>
}
export function Status({ value }: { value: string }) { return <span className={`asset-status ${Object.hasOwn(c.statuses, value) ? value.toLowerCase() : 'unknown'}`}><span aria-hidden="true">◷</span> {label(c.statuses, value)}</span> }
function asError(value: unknown) { return value instanceof ApiClientError ? value : new ApiClientError('Unable to load collection revision.', { code: 'UNKNOWN' }) }
