import { useEffect, useRef, useState } from 'react'
import { ApiClientError, createIntentKey } from '../../lib/api/client'
import type { VersionOptions } from '../assets/versionApi'
import type { StartInput } from './api'
import { impactCopy as c } from './copy'
export function AssessmentForm({ options, versions, initial, save, cancel }: { options: VersionOptions; versions: { id: string; label: string }[]; initial?: Partial<StartInput>; save: (input: StartInput, key: string) => Promise<void>; cancel: () => void }) {
  const [old, setOld] = useState(initial?.oldDirectionRevisionId ?? ''); const [target, setTarget] = useState(initial?.newDirectionRevisionId ?? ''); const [brief, setBrief] = useState(initial?.briefRevisionId ?? ''); const [mode, setMode] = useState<StartInput['mode']>(initial?.mode ?? 'RULES_ONLY'); const [scope, setScope] = useState(initial?.assetVersionIds ? 'explicit' : 'latest'); const [ids, setIds] = useState(initial?.assetVersionIds ?? []); const [error, setError] = useState<ApiClientError | null>(null); const [validation, setValidation] = useState(''); const [saving, setSaving] = useState(false); const busy = useRef(false); const intent = useRef<{ body: string; key: string } | null>(null); const form = useRef<HTMLFormElement>(null); const summary = useRef<HTMLDivElement>(null)
  useEffect(() => { form.current?.querySelector<HTMLElement>('select')?.focus() }, [])
  async function run(runMode = mode) {
    if (busy.current) return
    if (!target || (scope === 'explicit' && !ids.length)) { setValidation(c.required); queueMicrotask(() => summary.current?.focus()); return }
    if (old && old === target) { setValidation(c.invalid); queueMicrotask(() => summary.current?.focus()); return }
    const input: StartInput = { oldDirectionRevisionId: old || undefined, newDirectionRevisionId: target, briefRevisionId: brief || undefined, mode: runMode, includeImages: false, ...(scope === 'explicit' ? { assetVersionIds: ids } : {}) }
    const body = JSON.stringify(input); if (intent.current?.body !== body) intent.current = { body, key: createIntentKey() }
    busy.current = true; setSaving(true); setValidation(''); setError(null); setMode(runMode)
    try { await save(input, intent.current.key) } catch (value) { setError(value instanceof ApiClientError ? value : new ApiClientError('Unable to start assessment.', { code: 'UNKNOWN' })); queueMicrotask(() => summary.current?.focus()) } finally { busy.current = false; setSaving(false) }
  }
  return <form ref={form} className="asset-form" aria-label={c.start} onSubmit={event => { event.preventDefault(); void run() }}><h3>{c.start}</h3><p>{c.startNote}</p>{(error || validation) && <div ref={summary} tabIndex={-1} role="alert" className="project-error"><p>{error?.message ?? validation}</p>{error?.details.map((item, index) => <p key={index}>{item.message}</p>)}{error?.requestId && <p>{c.requestId}: {error.requestId}</p>}{error && <p>{c.failedWrite}</p>}{error?.code === 'AI_NOT_CONFIGURED' && <button type="button" disabled={saving} onClick={() => void run('RULES_ONLY')}>{c.fallback}</button>}</div>}
    <fieldset disabled={saving}><legend className="sr-only">{c.start}</legend><label>{c.old}<select value={old} onChange={event => setOld(event.target.value)}><option value="">{c.active}</option>{options.directions.map(value => <option key={value.id} value={value.id}>{value.label}</option>)}</select></label><label>{c.target}<select value={target} onChange={event => setTarget(event.target.value)}><option value="">{c.choose}</option>{options.directions.map(value => <option key={value.id} value={value.id}>{value.label}</option>)}</select></label><label>{c.brief}<select value={brief} onChange={event => setBrief(event.target.value)}><option value="">{c.latestBrief}</option>{options.briefs.map(value => <option key={value.id} value={value.id}>{value.label}</option>)}</select></label><label>{c.mode}<select value={mode} onChange={event => { const value = event.target.value; if (value === 'RULES_ONLY' || value === 'HYBRID' || value === 'AI_ASSISTED') setMode(value) }}>{Object.entries(c.modes).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>{c.scope}<select value={scope} onChange={event => setScope(event.target.value)}><option value="latest">{c.defaultScope}</option><option value="explicit">{c.explicitScope}</option></select></label><p>{c.scopeNote}</p>{scope === 'explicit' && <div className="impact-scope">{versions.map(version => <label key={version.id}><input type="checkbox" checked={ids.includes(version.id)} onChange={event => setIds(previous => event.target.checked ? [...previous, version.id] : previous.filter(id => id !== version.id))} />{version.label}<code>{version.id}</code></label>)}</div>}<p className="note">{c.imageNote}</p><div className="project-actions"><button>{saving ? c.saving : c.save}</button><button type="button" onClick={cancel}>{c.cancelForm}</button></div></fieldset>
  </form>
}
