import type { ResolveItemInput } from '../../../packages/contracts/src'
import { DecisionActions } from '../decisions/DecisionActions'
import { decisionCopy as d } from '../decisions/copy'
import type { AssessmentView, ItemView } from './api'
import { impactCopy as c } from './copy'
import { label } from '../references/display'
import { AssetMedia, AssetStatus } from '../assets/AssetMedia'
export function ImpactResults({ assessment, names, resolve, refresh }: { assessment: AssessmentView; names: { id: string; label: string }[]; resolve?: (item: ItemView, input: ResolveItemInput) => Promise<void>; refresh?: () => void }) {
  return <><div className="impact-context"><p><strong>{c.old}:</strong> {names.find(value => value.id === assessment.oldDirectionRevisionId)?.label ?? assessment.oldDirectionRevisionId ?? c.none}</p><p><strong>{c.target}:</strong> {names.find(value => value.id === assessment.newDirectionRevisionId)?.label ?? assessment.newDirectionRevisionId}</p><p><strong>{c.brief}:</strong> <code>{assessment.briefRevisionId ?? c.none}</code></p><p>{label(c.modes, assessment.mode)} · {assessment.rulesVersion} · {c.provider}: {assessment.providerName ?? c.unknown}</p>{assessment.isSimulated && <p className="simulated">{c.simulated}</p>}<p>{assessment.imagesSent === 0 ? c.noImages : `${c.images}: ${assessment.imagesSent}`}</p><p>{assessment.summary}</p></div><details className="home-panel"><summary>{c.diff}</summary><p>{assessment.directionDiff.summary}</p><dl>{assessment.directionDiff.changes.map((change, index) => <div key={index}><dt>{change.field}</dt><dd>{c.before}: {change.from ?? c.none}<br />{c.after}: {change.to ?? c.none}</dd></div>)}</dl></details><dl className="home-metrics"><div><dt>{c.total}</dt><dd>{assessment.counts.total}</dd></div><div><dt>{c.unresolved}</dt><dd>{assessment.counts.unresolved}</dd></div></dl><p>{c.counts}: {Object.entries(c.recommendations).map(([key, name]) => `${name}: ${assessment.counts.byRecommendation[key as keyof typeof assessment.counts.byRecommendation]}`).join(' · ')}</p><p className="impact-disclaimer">{c.disclaimer}</p>{assessment.status === 'COMPLETED' && <><p className="note">{c.decisionsLater}</p><ol className="impact-items">{assessment.items?.map(item => <ImpactItem key={item.id} item={item} projectId={assessment.projectId} resolve={resolve} refresh={refresh} />)}</ol></>}</>
}
function ImpactItem({ item, projectId, resolve, refresh }: { item: ItemView; projectId: string; resolve?: (item: ItemView, input: ResolveItemInput) => Promise<void>; refresh?: () => void }) { const evidence = (title: string, values: ItemView['supportingEvidence']) => <section><h5>{title}</h5>{values.length ? <ul>{values.map((value, index) => <li key={index}><p>{value.statement}</p><p className="note">{value.source} · {value.ruleId ?? c.none}</p>{value.sourceId && <code>{value.sourceId}</code>}</li>)}</ul> : <p>{c.none}</p>}</section>; return <li className="impact-item"><AssetMedia url={item.assetVersion.thumbnailUrl} title={item.assetVersion.assetTitle} /><div className="impact-item-body"><p>{c.priority} {item.priority} · {d.original}: <span className={`impact-badge ${Object.hasOwn(c.recommendations, item.recommendation) ? item.recommendation.toLowerCase() : 'unknown'}`}><span aria-hidden="true">◇</span> {label(c.recommendations, item.recommendation)}</span></p><h4>{item.assetVersion.assetTitle} · Version {item.assetVersion.versionNumber}</h4><AssetStatus status={item.assetVersion.status} version /><p><code>{item.assetVersion.id}</code></p><p>{item.rationale}</p><p>{c.priority}: {item.priorityReason}</p><p>{c.uncertainty}: {label(c.uncertainties, item.uncertaintyLevel)} · {c.source}: {label(c.sources, item.analysisSource)}</p>{item.requiresHumanReview && <p>{c.humanReview}</p>}<p>{c.resolution}: {label(c.resolutions, item.resolutionStatus)}</p><p>{c.effective}: {label(c.recommendations, item.effectiveRecommendation)}</p>{item.latestDecision && <section><h5>{d.currentLabel}</h5><p>{item.latestDecision.rationale}</p>{item.latestDecision.selectedAction && <p>{d.selected}: {item.latestDecision.selectedAction}</p>}<p>{d.actor}: {item.latestDecision.createdBy.displayName} | <time dateTime={item.latestDecision.createdAt}>{new Date(item.latestDecision.createdAt).toLocaleString()}</time></p><code>{item.latestDecision.id}</code></section>}{resolve && <DecisionActions item={item} save={resolve} refresh={refresh ?? (() => {})} />}{evidence(c.supporting, item.supportingEvidence)}{evidence(c.conflicting, item.conflictingEvidence)}<section><h5>{c.missing}</h5>{item.missingInformation.length ? <ul>{item.missingInformation.map((value, index) => <li key={index}>{value}</li>)}</ul> : <p>{c.none}</p>}</section><section><h5>{c.actions}</h5><ul>{item.suggestedActions.map((value, index) => <li key={index}>{value}</li>)}</ul></section><a href={`#/projects/${projectId}/assets/${item.assetVersion.assetId}/versions/${item.assetVersion.id}`}>{c.inspect}</a></div></li> }
