import { useEffect, useMemo, useRef, useState } from 'react'
import { ApiClientError, type ApiClient } from '../../lib/api/client'
import { decisionApi, type DecisionView } from './api'
import { decisionCopy as c } from './copy'
import { impactCopy } from '../impact/copy'
import { label } from '../references/display'
export function DecisionHistory({ client, projectId, assessmentId, refresh = 0 }: { client: ApiClient; projectId: string; assessmentId?: string; refresh?: number }) {
  const api = useMemo(() => decisionApi(client), [client]); const [query, setQuery] = useState({ decisionType: '', currentOnly: false, assetId: '', assetVersionId: '', collectionRevisionId: '', assessmentId: '' }); const [items, setItems] = useState<DecisionView[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [moreLoading, setMoreLoading] = useState(false); const [error, setError] = useState<ApiClientError | null>(null); const [attempt, setAttempt] = useState(0); const generation = useRef(0); const paging = useRef(false)
  const filters = useMemo(() => ({ ...Object.fromEntries(Object.entries(query).map(([key, value]) => [key, value === '' ? undefined : value])), ...(assessmentId ? { assessmentId } : {}) }), [query, assessmentId])
  useEffect(() => { const controller = new AbortController(); const current = ++generation.current; paging.current = false
    // oxlint-disable-next-line react/set-state-in-effect -- Synchronize decision history with server filters and confirmed writes.
    setLoading(true); setError(null); setMoreLoading(false); setItems([]); setCursor(null)
    api.list(projectId, filters, controller.signal).then(result => { if (result.data.some(value => value.projectId !== projectId)) throw new ApiClientError('Decision history belongs to another project.', { code: 'CROSS_PROJECT_REFERENCE' }); if (!controller.signal.aborted && current === generation.current) { setItems(result.data); setCursor(result.page.nextCursor); setLoading(false) } }).catch(value => { if (!controller.signal.aborted) { setError(asError(value)); setLoading(false) } }); return () => controller.abort()
  }, [api, projectId, filters, attempt, refresh])
  async function more() { if (!cursor || paging.current) return; paging.current = true; setMoreLoading(true); const current = generation.current; try { const result = await api.list(projectId, { ...filters, cursor }); if (result.data.some(value => value.projectId !== projectId)) throw new ApiClientError('Decision history belongs to another project.', { code: 'CROSS_PROJECT_REFERENCE' }); if (current === generation.current) { setItems(previous => [...previous, ...result.data]); setCursor(result.page.nextCursor); setError(null) } } catch (value) { if (current === generation.current) setError(asError(value)) } finally { if (current === generation.current) { paging.current = false; setMoreLoading(false) } } }
  return <section className="home-panel decision-history" aria-label={c.heading}><h3>{c.heading}</h3><button onClick={() => setAttempt(value => value + 1)} disabled={loading}>{c.refresh}</button><div className="impact-filters"><label>{c.type}<select value={query.decisionType} onChange={event => setQuery(previous => ({ ...previous, decisionType: event.target.value }))}><option value="">{c.all}</option>{Object.entries(c.types).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><label className="asset-checkbox"><input type="checkbox" checked={query.currentOnly} onChange={event => setQuery(previous => ({ ...previous, currentOnly: event.target.checked }))} />{c.current}</label></div><details><summary>Filter by exact record IDs</summary>{(['assessmentId', 'assetId', 'assetVersionId', 'collectionRevisionId'] as const).filter(field => field !== 'assessmentId' || !assessmentId).map(field => <label key={field}>{({ assessmentId: 'Assessment ID', assetId: 'Asset ID', assetVersionId: 'Asset version ID', collectionRevisionId: 'Collection revision ID' })[field]}<input value={query[field]} onChange={event => setQuery(previous => ({ ...previous, [field]: event.target.value.trim() }))} /></label>)}</details>
    {error && <div className="project-error" role="alert"><p>{error.message}</p>{error.requestId && <p>{c.requestId}: {error.requestId}</p>}<button onClick={() => setAttempt(value => value + 1)}>{c.retry}</button></div>}{loading ? <p role="status">{c.loading}</p> : <>{!error && !items.length && <p>{Object.values(query).some(Boolean) ? c.noResults : c.empty}</p>}<ol className="decision-list">{items.map(decision => <li key={decision.id}><h4>{label(c.types, decision.decisionType)}</h4><p>{decision.supersededByDecisionId ? c.superseded : c.currentLabel}</p><p>{decision.rationale}</p>{decision.selectedAction && <p>{c.selected}: {decision.selectedAction}</p>}<p>{c.actor}: {decision.createdBy.displayName} · <time dateTime={decision.createdAt}>{new Date(decision.createdAt).toLocaleString()}</time></p>{decision.previousRecommendation && <p>Previous recommendation: {label(impactCopy.recommendations, decision.previousRecommendation)}</p>}{decision.newRecommendation && <p>Recorded recommendation: {label(impactCopy.recommendations, decision.newRecommendation)}</p>}<p>Decision ID: <code>{decision.id}</code></p>{decision.supersedesDecisionId && <p>Supersedes: <code>{decision.supersedesDecisionId}</code></p>}{decision.supersededByDecisionId && <p>Superseded by: <code>{decision.supersededByDecisionId}</code></p>}{decision.assessmentItemId && <p>Assessment item ID: <code>{decision.assessmentItemId}</code></p>}{decision.directionRevisionId && <p>Direction revision ID: <code>{decision.directionRevisionId}</code></p>}{decision.collectionRevisionId && <p>Collection revision ID: <code>{decision.collectionRevisionId}</code></p>}{decision.assetId && <a href={`#/projects/${projectId}/assets/${decision.assetId}${decision.assetVersionId ? `/versions/${decision.assetVersionId}` : ''}`}>Inspect recorded asset version</a>}</li>)}</ol>{cursor && <button disabled={moreLoading} onClick={() => void more()}>{moreLoading ? c.loading : c.more}</button>}</>}
  </section>
}
function asError(value: unknown) { return value instanceof ApiClientError ? value : new ApiClientError('Unable to load decision history.', { code: 'UNKNOWN' }) }
