import { useEffect, useRef, useState } from 'react'
import { ResolveItemInputSchema, type ResolveItemInput } from '../../../packages/contracts/src'
import { ApiClientError } from '../../lib/api/client'
import type { ItemView } from '../impact/api'
import { impactCopy } from '../impact/copy'
import { decisionCopy as c } from './copy'
export function DecisionForm({ item, save, cancel, refresh }: { item: ItemView; save: (input: ResolveItemInput) => Promise<void>; cancel: () => void; refresh: () => void }) {
  const [resolution, setResolution] = useState('ACCEPT'); const [override, setOverride] = useState(''); const [rationale, setRationale] = useState(''); const [selectedAction, setSelectedAction] = useState(''); const [errors, setErrors] = useState<Record<string, string>>({}); const [error, setError] = useState<ApiClientError | null>(null); const [saving, setSaving] = useState(false); const busy = useRef(false); const form = useRef<HTMLFormElement>(null); const summary = useRef<HTMLDivElement>(null)
  useEffect(() => { form.current?.querySelector<HTMLElement>('select')?.focus() }, [])
  async function submit() {
    if (busy.current) return
    const parsed = ResolveItemInputSchema.safeParse({ resolution, overrideRecommendation: resolution === 'OVERRIDE' ? override || undefined : undefined, rationale: rationale.trim() || undefined, selectedAction: selectedAction.trim() || null })
    const values: Record<string, string> = {}; if (!parsed.success) for (const issue of parsed.error.issues) values[String(issue.path[0])] = issue.message
    if (resolution === 'OVERRIDE' && override === item.recommendation) values.overrideRecommendation = 'Choose a recommendation different from the original recommendation.'
    if (Object.keys(values).length || !parsed.success) { setErrors(values); queueMicrotask(() => summary.current?.focus()); return }
    busy.current = true; setSaving(true); setError(null); setErrors({})
    try { await save(parsed.data) } catch (value) { const error = value instanceof ApiClientError ? value : new ApiClientError('Unable to save decision.', { code: 'UNKNOWN' }); setError(error); setErrors(Object.fromEntries(error.details.map(detail => [detail.path.replace(/^body\./, ''), detail.message]))); queueMicrotask(() => summary.current?.focus()) } finally { busy.current = false; setSaving(false) }
  }
  return <form ref={form} className="asset-form decision-form" aria-label={`Record decision: ${item.assetVersion.assetTitle}`} onSubmit={event => { event.preventDefault(); void submit() }}><h5>{item.latestDecision ? c.update : c.record}</h5><p>{c.intent}</p>{item.latestDecision && <p>{c.append}</p>}<p>{c.comment}</p>{(error || Object.keys(errors).length > 0) && <div role="alert" ref={summary} tabIndex={-1} className="project-error"><p>{error?.message ?? 'Check the decision fields.'}</p>{Object.values(errors).map((value, index) => <p key={index}>{value}</p>)}{error?.requestId && <p>{c.requestId}: {error.requestId}</p>}{error && <><p>{c.uncertain}</p><button type="button" onClick={refresh}>{c.refresh}</button></>}</div>}
    <fieldset disabled={saving}><label>{c.action}<select value={resolution} onChange={event => setResolution(event.target.value)}>{Object.entries(c.actions).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label>{resolution === 'OVERRIDE' && <div><label>{c.override}<select value={override} aria-invalid={Boolean(errors.overrideRecommendation)} aria-describedby={`decision-override-${item.id}`} onChange={event => setOverride(event.target.value)}><option value="">{c.choose}</option>{Object.entries(impactCopy.recommendations).filter(([key]) => key !== item.recommendation).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><p id={`decision-override-${item.id}`} className="field-error">{errors.overrideRecommendation}</p></div>}<div><label>{c.rationale}<textarea value={rationale} aria-invalid={Boolean(errors.rationale)} aria-describedby={`decision-rationale-${item.id}`} onChange={event => setRationale(event.target.value)} /></label><p id={`decision-rationale-${item.id}`} className="field-error">{errors.rationale}</p></div><label>{c.selected}<input value={selectedAction} list={`decision-actions-${item.id}`} onChange={event => setSelectedAction(event.target.value)} /></label><datalist id={`decision-actions-${item.id}`}>{item.suggestedActions.map((action, index) => <option key={index} value={action} />)}</datalist><div className="project-actions"><button>{saving ? c.saving : c.save}</button><button type="button" onClick={cancel}>{c.cancel}</button></div></fieldset>
  </form>
}
