import { z } from 'zod'

export const CONTRACT_VERSION = '1.0.0'
export const UUIDSchema = z.uuid()
export type UUID = z.infer<typeof UUIDSchema>
export const ISODateTimeSchema = z.iso.datetime()
export type ISODateTime = z.infer<typeof ISODateTimeSchema>
const text = z.string()
const nullableText = text.nullable()
const id = UUIDSchema
const nullableId = id.nullable()
const date = ISODateTimeSchema
const nullableDate = date.nullable()
const count = z.number().int().nonnegative()
const number = z.number().int().positive()
const strings = z.array(text)
const record = z.record(text, z.unknown())

export const ProjectStatusSchema = z.enum(['ACTIVE', 'ARCHIVED'])
export const ProjectRoleSchema = z.enum(['OWNER', 'EDITOR', 'REVIEWER', 'VIEWER'])
export const DirectionStatusSchema = z.enum(['DRAFT', 'ACTIVE', 'SUPERSEDED', 'ARCHIVED'])
export const AssetTypeSchema = z.enum(['HERO_IMAGE', 'PRODUCT_IMAGE', 'BACKGROUND', 'TEXTURE', 'CHARACTER', 'CONCEPT_ART', 'LAYOUT', 'OTHER'])
export const AssetStatusSchema = z.enum(['DRAFT', 'IN_PROGRESS', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', 'ARCHIVED'])
export const AssetVersionStatusSchema = z.enum(['DRAFT', 'CANDIDATE', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED'])
export const RecommendationSchema = z.enum(['REUSE_CANDIDATE', 'ADAPT_CANDIDATE', 'REVIEW_REQUIRED', 'RECREATE_CANDIDATE'])
export const UncertaintyLevelSchema = z.enum(['LOW', 'MEDIUM', 'HIGH'])
export const AnalysisSourceSchema = z.enum(['RULES', 'AI', 'HYBRID'])
export const AssessmentModeSchema = z.enum(['RULES_ONLY', 'AI_ASSISTED', 'HYBRID'])
export const AssessmentStatusSchema = z.enum(['PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'])
export const ResolutionStatusSchema = z.enum(['UNRESOLVED', 'ACCEPTED', 'OVERRIDDEN', 'DISMISSED', 'DEFERRED'])
export const ResolutionActionSchema = z.enum(['ACCEPT', 'OVERRIDE', 'DEFER', 'DISMISS'])
export const DecisionTypeSchema = z.enum(['ACCEPT_RECOMMENDATION', 'OVERRIDE_RECOMMENDATION', 'DISMISS_RECOMMENDATION', 'DEFER_RECOMMENDATION', 'APPROVE_VERSION', 'REJECT_VERSION', 'REQUEST_REVISION', 'CHANGE_DIRECTION', 'PIN_TO_COLLECTION', 'REPLACE_PINNED_VERSION'])
export const CollectionTypeSchema = z.enum(['DELIVERABLE', 'REVIEW_ROUND', 'PRESENTATION', 'OTHER'])
export const CollectionStatusSchema = z.enum(['DRAFT', 'IN_REVIEW', 'APPROVED', 'SUPERSEDED', 'ARCHIVED'])
export const CollectionRevisionStatusSchema = z.enum(['DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED'])
export const ApprovalDecisionSchema = z.enum(['APPROVED', 'CHANGES_REQUESTED', 'REJECTED'])
export const ReferenceSourceTypeSchema = z.enum(['USER_UPLOAD', 'PUBLIC_URL', 'INTERNAL_ASSET', 'DEMO_ASSET'])
export const AttributeCategorySchema = z.enum(['PALETTE', 'LIGHTING', 'COMPOSITION', 'MATERIAL', 'MOOD', 'TYPOGRAPHY', 'SUBJECT', 'OTHER'])
export const AttributeOriginSchema = z.enum(['USER_PROVIDED', 'AI_INFERRED', 'SYSTEM_DERIVED'])
export const AttributeReviewStatusSchema = z.enum(['UNREVIEWED', 'CONFIRMED', 'CORRECTED', 'REJECTED'])
export const EvidenceSourceSchema = z.enum(['BRIEF', 'DIRECTION', 'ASSET_METADATA', 'IMAGE_OBSERVATION', 'USER_NOTE', 'RULE'])
export const ErrorCodeSchema = z.enum(['VALIDATION_ERROR', 'UNAUTHENTICATED', 'FORBIDDEN', 'NOT_FOUND', 'CONFLICT', 'INVALID_STATE_TRANSITION', 'REVISION_FROZEN', 'OPEN_REVISION_EXISTS', 'ASSET_ALREADY_PINNED', 'IDEMPOTENCY_KEY_REUSED', 'CROSS_PROJECT_REFERENCE', 'ASSESSMENT_SCOPE_TOO_LARGE', 'AI_NOT_CONFIGURED', 'AI_BUDGET_EXCEEDED', 'NO_IMAGE_INPUT', 'PAYLOAD_TOO_LARGE', 'UNSUPPORTED_MEDIA_TYPE', 'RATE_LIMITED', 'PROVIDER_ERROR', 'PROVIDER_TIMEOUT', 'INTERNAL_ERROR'])

export const ResponseMetaSchema = z.object({ simulated: z.boolean().optional() })
export const ErrorDetailSchema = z.object({ path: text, message: text, code: text.optional() })
export const ApiErrorSchema = z.object({ error: z.object({ code: ErrorCodeSchema, message: text, requestId: text, details: z.array(ErrorDetailSchema) }) })
export function ApiResponseSchema<T extends z.ZodType>(schema: T) { return z.object({ data: schema, meta: ResponseMetaSchema.optional() }) }
export function ApiListSchema<T extends z.ZodType>(schema: T) { return z.object({ data: z.array(schema), page: z.object({ limit: number.max(100), nextCursor: nullableText }) }) }
export interface ApiResponse<T> { data: T; meta?: ResponseMeta }
export interface ApiList<T> { data: T[]; page: { limit: number; nextCursor: string | null } }

export const UserSummarySchema = z.object({ id, displayName: text })
export const AttributeRequirementSchema = z.object({ id, category: AttributeCategorySchema, label: text, value: text, hard: z.boolean() })
export const PaletteColorSchema = z.object({ name: text, hex: text.regex(/^#[0-9a-fA-F]{6}$/).nullable(), role: nullableText })
export const LightingSpecSchema = z.object({ quality: nullableText, direction: nullableText, temperature: nullableText, notes: nullableText })
export const CompositionSpecSchema = z.object({ framing: nullableText, layout: nullableText, notes: nullableText })
export const TypographySpecSchema = z.object({ families: strings, notes: nullableText })
export const RecordedAttributesSchema = z.object({ palette: strings, lighting: strings, composition: strings, materials: strings, mood: strings, typography: strings, subject: strings })
export const EvidenceSchema = z.object({ source: EvidenceSourceSchema, statement: text, sourceId: nullableId, ruleId: nullableText })
export const ProjectSchema = z.object({ id, name: text, slug: text, description: nullableText, status: ProjectStatusSchema, owner: UserSummarySchema, currentUserRole: ProjectRoleSchema, activeDirectionRevisionId: nullableId, createdAt: date, updatedAt: date, archivedAt: nullableDate })
export const BriefRevisionSchema = z.object({ id, projectId: id, revisionNumber: number, title: text, objective: text, targetAudience: nullableText, deliverables: strings, requirements: z.array(AttributeRequirementSchema), constraints: strings, forbiddenAttributes: z.array(AttributeRequirementSchema), acceptanceCriteria: strings, sourceText: nullableText, changeSummary: nullableText, createdBy: UserSummarySchema, createdAt: date })
export const BriefRevisionInputSchema = BriefRevisionSchema.omit({ id: true, projectId: true, revisionNumber: true, createdBy: true, createdAt: true })
export const DirectionRevisionSchema = z.object({ id, directionId: id, revisionNumber: number, summary: text, palette: z.array(PaletteColorSchema), lighting: LightingSpecSchema, composition: CompositionSpecSchema, materials: strings, mood: strings, typography: TypographySpecSchema, requiredAttributes: z.array(AttributeRequirementSchema), forbiddenAttributes: z.array(AttributeRequirementSchema), stylePrompt: nullableText, changeSummary: nullableText, createdBy: UserSummarySchema, createdAt: date })
export const DirectionRevisionInputSchema = DirectionRevisionSchema.omit({ id: true, directionId: true, revisionNumber: true, createdBy: true, createdAt: true })
export const DirectionSchema = z.object({ id, projectId: id, name: text, description: nullableText, status: DirectionStatusSchema, isActive: z.boolean(), latestRevision: DirectionRevisionSchema, revisionCount: number, createdBy: UserSummarySchema, createdAt: date, updatedAt: date, archivedAt: nullableDate })
export const DirectionDiffChangeSchema = z.object({ category: z.union([AttributeCategorySchema, z.enum(['SUMMARY', 'STYLE_PROMPT'])]), field: text, from: nullableText, to: nullableText, kind: z.enum(['ADDED', 'REMOVED', 'CHANGED']) })
export const DirectionDiffSchema = z.object({ fromRevisionId: nullableId, toRevisionId: id, summary: text, changes: z.array(DirectionDiffChangeSchema) })
export const ActiveDirectionChangeResultSchema = z.object({ project: ProjectSchema, previousDirectionRevisionId: nullableId, decisionId: id })
export const StorageObjectSchema = z.object({ id, originalFilename: nullableText, mimeType: text, byteSize: count, width: number.nullable(), height: number.nullable(), checksum: nullableText, url: text, urlExpiresAt: nullableDate, createdAt: date })
export const ReferenceAttributeSchema = z.object({ id, referenceId: id, attributeType: AttributeCategorySchema, value: z.object({ text, hex: nullableText }), origin: AttributeOriginSchema, reviewStatus: AttributeReviewStatusSchema, createdBy: UserSummarySchema.nullable(), createdAt: date, updatedAt: date })
export const ReferenceLinkSchema = z.object({ targetType: z.enum(['DIRECTION_REVISION', 'ASSET', 'ASSET_VERSION']), targetId: id, relationshipType: nullableText, usageNote: nullableText })
export const ReferenceLinkInputSchema = ReferenceLinkSchema.extend({ relationshipType: nullableText.optional(), usageNote: nullableText.optional() })
export const ReferenceSchema = z.object({ id, projectId: id, title: text, description: nullableText, sourceType: ReferenceSourceTypeSchema, sourceUrl: nullableText, usageRightsNote: nullableText, tags: strings, fileUrl: nullableText, thumbnailUrl: nullableText, attributes: z.array(ReferenceAttributeSchema), links: z.array(ReferenceLinkSchema), addedBy: UserSummarySchema, createdAt: date, updatedAt: date, archivedAt: nullableDate })
export const AssetVersionSummarySchema = z.object({ id, assetId: id, versionNumber: number, status: AssetVersionStatusSchema, thumbnailUrl: nullableText, createdAt: date })
export const AssetVersionRefSchema = AssetVersionSummarySchema.extend({ assetTitle: text, assetType: AssetTypeSchema })
export const AssetSchema = z.object({ id, projectId: id, title: text, description: nullableText, assetType: AssetTypeSchema, status: AssetStatusSchema, tags: strings, owner: UserSummarySchema.nullable(), versionCount: count, latestVersion: AssetVersionSummarySchema.nullable(), createdBy: UserSummarySchema, createdAt: date, updatedAt: date, archivedAt: nullableDate })
export const DecisionSchema = z.object({ id, projectId: id, assessmentItemId: nullableId, assetId: nullableId, assetVersionId: nullableId, directionRevisionId: nullableId, collectionRevisionId: nullableId, decisionType: DecisionTypeSchema, selectedAction: nullableText, rationale: text, previousRecommendation: RecommendationSchema.nullable(), newRecommendation: RecommendationSchema.nullable(), supersedesDecisionId: nullableId, supersededByDecisionId: nullableId, createdBy: UserSummarySchema, createdAt: date })
export const AssetDetailSchema = AssetSchema.extend({ versions: z.array(AssetVersionSummarySchema), referenceLinks: z.array(z.object({ referenceId: id, relationshipType: text, note: nullableText })), recentDecisions: z.array(DecisionSchema) })
export const AssetVersionSchema = z.object({ id, assetId: id, assetTitle: text, versionNumber: number, derivedFromVersionId: nullableId, directionRevisionId: nullableId, briefRevisionId: nullableId, fileUrl: nullableText, thumbnailUrl: nullableText, externalFileUrl: nullableText, isMetadataOnly: z.boolean(), mimeType: nullableText, width: number.nullable(), height: number.nullable(), contentChecksum: nullableText, prompt: nullableText, negativePrompt: nullableText, providerName: nullableText, modelName: nullableText, modelVersion: nullableText, generationSettings: record, recordedAttributes: RecordedAttributesSchema, revisionRationale: text, status: AssetVersionStatusSchema, references: z.array(z.object({ referenceId: id, usageNote: nullableText })), isLatest: z.boolean(), pinnedIn: z.array(z.object({ collectionId: id, collectionName: text, collectionRevisionId: id, revisionNumber: number, revisionStatus: CollectionRevisionStatusSchema })), lineage: z.object({ derivedFrom: AssetVersionSummarySchema.nullable(), derivedVersions: z.array(AssetVersionSummarySchema) }), createdBy: UserSummarySchema, createdAt: date })
export const AssetVersionInputSchema = z.object({ derivedFromVersionId: nullableId.optional(), directionRevisionId: nullableId.optional(), briefRevisionId: nullableId.optional(), storageObjectId: nullableId.optional(), thumbnailStorageObjectId: nullableId.optional(), externalFileUrl: nullableText.optional(), metadataOnly: z.boolean().optional(), mimeType: nullableText.optional(), width: number.nullable().optional(), height: number.nullable().optional(), prompt: nullableText.optional(), negativePrompt: nullableText.optional(), providerName: nullableText.optional(), modelName: nullableText.optional(), modelVersion: nullableText.optional(), generationSettings: record.optional(), recordedAttributes: RecordedAttributesSchema.partial().optional(), revisionRationale: text.min(3), references: z.array(z.object({ referenceId: id, usageNote: nullableText.optional() })).optional(), status: z.enum(['DRAFT', 'CANDIDATE', 'NEEDS_REVIEW']).optional() })
export const ImpactAssessmentItemSchema = z.object({ id, assessmentId: id, assetVersion: AssetVersionRefSchema, recommendation: RecommendationSchema, rationale: text, supportingEvidence: z.array(EvidenceSchema), conflictingEvidence: z.array(EvidenceSchema), missingInformation: strings, suggestedActions: strings, uncertaintyLevel: UncertaintyLevelSchema, requiresHumanReview: z.boolean(), analysisSource: AnalysisSourceSchema, priority: number, priorityReason: text, resolutionStatus: ResolutionStatusSchema, effectiveRecommendation: RecommendationSchema, latestDecision: DecisionSchema.nullable(), createdAt: date, updatedAt: date })
export const ImpactAssessmentSchema = z.object({ id, projectId: id, oldDirectionRevisionId: nullableId, newDirectionRevisionId: id, briefRevisionId: nullableId, mode: AssessmentModeSchema, status: AssessmentStatusSchema, providerName: nullableText, modelName: nullableText, promptTemplateVersion: nullableText, outputSchemaVersion: text, rulesVersion: text, isSimulated: z.boolean(), imagesSent: count, directionDiff: DirectionDiffSchema, summary: nullableText, errorCode: nullableText, errorSummary: nullableText, counts: z.object({ total: count, byRecommendation: z.record(RecommendationSchema, count), unresolved: count }), items: z.array(ImpactAssessmentItemSchema).nullable(), startedBy: UserSummarySchema, startedAt: date, completedAt: nullableDate })
export const ResolveItemInputSchema = z.object({ resolution: ResolutionActionSchema, overrideRecommendation: RecommendationSchema.optional(), selectedAction: nullableText.optional(), rationale: text.optional() }).superRefine((value, ctx) => {
  if (value.resolution === 'OVERRIDE' && !value.overrideRecommendation) ctx.addIssue({ code: 'custom', path: ['overrideRecommendation'], message: 'Choose an override recommendation.' })
  if (['OVERRIDE', 'DISMISS'].includes(value.resolution) && (value.rationale?.trim().length ?? 0) < 5) ctx.addIssue({ code: 'custom', path: ['rationale'], message: 'Provide a rationale of at least 5 characters.' })
})
export const CollectionItemSchema = z.object({ id, collectionRevisionId: id, position: number, role: nullableText, note: nullableText, pinnedVersion: AssetVersionRefSchema, latestVersion: AssetVersionRefSchema, isStale: z.boolean(), newerVersionCount: count })
export const ApprovalSchema = z.object({ id, collectionRevisionId: id, decision: ApprovalDecisionSchema, comment: nullableText, reviewedBy: UserSummarySchema, reviewedAt: date })
export const CollectionRevisionSummarySchema = z.object({ id, collectionId: id, revisionNumber: number, status: CollectionRevisionStatusSchema, changeSummary: nullableText, itemCount: count, staleItemCount: count, createdBy: UserSummarySchema, createdAt: date, submittedAt: nullableDate, approvedAt: nullableDate })
export const CollectionRevisionSchema = CollectionRevisionSummarySchema.extend({ collectionName: text, items: z.array(CollectionItemSchema), approvals: z.array(ApprovalSchema) })
export const CollectionSchema = z.object({ id, projectId: id, name: text, description: nullableText, collectionType: CollectionTypeSchema, status: CollectionStatusSchema, latestRevision: CollectionRevisionSummarySchema, approvedRevisionId: nullableId, createdBy: UserSummarySchema, createdAt: date, updatedAt: date, archivedAt: nullableDate })
export const CollectionDetailSchema = CollectionSchema.extend({ revisions: z.array(CollectionRevisionSummarySchema) })
export const ActivityEventTypeSchema = z.enum(['PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_ARCHIVED', 'PROJECT_RESTORED', 'BRIEF_REVISION_CREATED', 'DIRECTION_CREATED', 'DIRECTION_REVISION_CREATED', 'ACTIVE_DIRECTION_CHANGED', 'REFERENCE_ADDED', 'REFERENCE_UPDATED', 'REFERENCE_LINKED', 'REFERENCE_ATTRIBUTE_REVIEWED', 'ASSET_CREATED', 'ASSET_UPDATED', 'ASSET_VERSION_CREATED', 'ASSET_VERSION_STATUS_CHANGED', 'ASSESSMENT_STARTED', 'ASSESSMENT_COMPLETED', 'ASSESSMENT_FAILED', 'ASSESSMENT_CANCELLED', 'RECOMMENDATION_RESOLVED', 'COLLECTION_CREATED', 'COLLECTION_REVISION_CREATED', 'COLLECTION_ITEM_PINNED', 'COLLECTION_ITEM_REPLACED', 'COLLECTION_SUBMITTED', 'COLLECTION_APPROVED', 'COLLECTION_REVIEW_REJECTED', 'EXPORT_CREATED', 'DEMO_RESET'])
export const ActivityEventSchema = z.object({ id, projectId: id, actor: UserSummarySchema.nullable(), eventType: text, entityType: text, entityId: nullableId, summary: text, metadata: record, requestId: nullableText, createdAt: date })
export const ExportResultSchema = z.object({ id, format: z.enum(['JSON', 'MARKDOWN', 'CSV']), filename: text, contentType: text, content: text, warnings: z.array(z.object({ code: z.enum(['LOCAL_ONLY_FILE_PATHS', 'METADATA_ONLY_VERSIONS', 'OTHER']), message: text })), createdAt: date })
export const AiSettingsSchema = z.object({ mode: z.enum(['mock', 'openai']), providerConfigured: z.boolean(), modelName: nullableText, imageAnalysisAvailable: z.boolean(), maxAssetsPerAssessment: number, monthlyBudgetLimitUsd: z.number().nonnegative().nullable(), monthToDateCostUsd: z.number().nonnegative().nullable() })
export const AiTestResultSchema = z.object({ ok: z.boolean(), latencyMs: count.nullable(), errorCode: nullableText, message: text })
export const HealthStatusSchema = z.object({ status: z.literal('ok'), apiVersion: text, contractVersion: text, aiMode: z.enum(['mock', 'openai']), demoMode: z.boolean(), authMode: z.enum(['demo', 'session']) })
export const ProjectSummarySchema = z.object({ project: ProjectSchema, activeDirection: z.object({ direction: DirectionSchema, revision: DirectionRevisionSchema }).nullable(), assetCounts: z.object({ total: count, byStatus: z.record(AssetStatusSchema, count) }), unresolvedRecommendationCount: count, staleCollectionItemCount: count, latestAssessment: z.object({ id, status: AssessmentStatusSchema, startedAt: date, isSimulated: z.boolean() }).nullable(), recentDecisions: z.array(DecisionSchema) })

export type ProjectStatus = z.infer<typeof ProjectStatusSchema>
export type ProjectRole = z.infer<typeof ProjectRoleSchema>
export type DirectionStatus = z.infer<typeof DirectionStatusSchema>
export type AssetType = z.infer<typeof AssetTypeSchema>
export type AssetStatus = z.infer<typeof AssetStatusSchema>
export type AssetVersionStatus = z.infer<typeof AssetVersionStatusSchema>
export type Recommendation = z.infer<typeof RecommendationSchema>
export type UncertaintyLevel = z.infer<typeof UncertaintyLevelSchema>
export type AnalysisSource = z.infer<typeof AnalysisSourceSchema>
export type AssessmentMode = z.infer<typeof AssessmentModeSchema>
export type AssessmentStatus = z.infer<typeof AssessmentStatusSchema>
export type ResolutionStatus = z.infer<typeof ResolutionStatusSchema>
export type ResolutionAction = z.infer<typeof ResolutionActionSchema>
export type DecisionType = z.infer<typeof DecisionTypeSchema>
export type CollectionType = z.infer<typeof CollectionTypeSchema>
export type CollectionStatus = z.infer<typeof CollectionStatusSchema>
export type CollectionRevisionStatus = z.infer<typeof CollectionRevisionStatusSchema>
export type ApprovalDecision = z.infer<typeof ApprovalDecisionSchema>
export type ReferenceSourceType = z.infer<typeof ReferenceSourceTypeSchema>
export type AttributeCategory = z.infer<typeof AttributeCategorySchema>
export type AttributeOrigin = z.infer<typeof AttributeOriginSchema>
export type AttributeReviewStatus = z.infer<typeof AttributeReviewStatusSchema>
export type EvidenceSource = z.infer<typeof EvidenceSourceSchema>
export type ErrorCode = z.infer<typeof ErrorCodeSchema>
export type ResponseMeta = z.infer<typeof ResponseMetaSchema>
export type ErrorDetail = z.infer<typeof ErrorDetailSchema>
export type ApiError = z.infer<typeof ApiErrorSchema>
export type UserSummary = z.infer<typeof UserSummarySchema>
export type AttributeRequirement = z.infer<typeof AttributeRequirementSchema>
export type PaletteColor = z.infer<typeof PaletteColorSchema>
export type LightingSpec = z.infer<typeof LightingSpecSchema>
export type CompositionSpec = z.infer<typeof CompositionSpecSchema>
export type TypographySpec = z.infer<typeof TypographySpecSchema>
export type RecordedAttributes = z.infer<typeof RecordedAttributesSchema>
export type Evidence = z.infer<typeof EvidenceSchema>
export type Project = z.infer<typeof ProjectSchema>
export type BriefRevision = z.infer<typeof BriefRevisionSchema>
export type BriefRevisionInput = z.infer<typeof BriefRevisionInputSchema>
export type DirectionRevision = z.infer<typeof DirectionRevisionSchema>
export type DirectionRevisionInput = z.infer<typeof DirectionRevisionInputSchema>
export type Direction = z.infer<typeof DirectionSchema>
export type DirectionDiffChange = z.infer<typeof DirectionDiffChangeSchema>
export type DirectionDiff = z.infer<typeof DirectionDiffSchema>
export type ActiveDirectionChangeResult = z.infer<typeof ActiveDirectionChangeResultSchema>
export type StorageObject = z.infer<typeof StorageObjectSchema>
export type ReferenceAttribute = z.infer<typeof ReferenceAttributeSchema>
export type ReferenceLink = z.infer<typeof ReferenceLinkSchema>
export type ReferenceLinkInput = z.infer<typeof ReferenceLinkInputSchema>
export type Reference = z.infer<typeof ReferenceSchema>
export type AssetVersionSummary = z.infer<typeof AssetVersionSummarySchema>
export type AssetVersionRef = z.infer<typeof AssetVersionRefSchema>
export type Asset = z.infer<typeof AssetSchema>
export type Decision = z.infer<typeof DecisionSchema>
export type AssetDetail = z.infer<typeof AssetDetailSchema>
export type AssetVersion = z.infer<typeof AssetVersionSchema>
export type AssetVersionInput = z.infer<typeof AssetVersionInputSchema>
export type ImpactAssessmentItem = z.infer<typeof ImpactAssessmentItemSchema>
export type ImpactAssessment = z.infer<typeof ImpactAssessmentSchema>
export type ResolveItemInput = z.infer<typeof ResolveItemInputSchema>
export type CollectionItem = z.infer<typeof CollectionItemSchema>
export type Approval = z.infer<typeof ApprovalSchema>
export type CollectionRevisionSummary = z.infer<typeof CollectionRevisionSummarySchema>
export type CollectionRevision = z.infer<typeof CollectionRevisionSchema>
export type Collection = z.infer<typeof CollectionSchema>
export type CollectionDetail = z.infer<typeof CollectionDetailSchema>
export type ActivityEventType = z.infer<typeof ActivityEventTypeSchema>
export type ActivityEvent = z.infer<typeof ActivityEventSchema>
export type ExportResult = z.infer<typeof ExportResultSchema>
export type AiSettings = z.infer<typeof AiSettingsSchema>
export type AiTestResult = z.infer<typeof AiTestResultSchema>
export type HealthStatus = z.infer<typeof HealthStatusSchema>
export type ProjectSummary = z.infer<typeof ProjectSummarySchema>
