import { expect, test } from '@playwright/test'
test('filters assets, preserves library context, creates metadata and keeps version history immutable', async ({ page }) => {
  await page.goto('/#/projects/00000000-0000-4000-8000-000000000010')
  await page.getByRole('link', { name: 'View assets' }).click()
  await expect(page.getByRole('heading', { name: 'Hero Product Reveal' })).toBeVisible()
  await expect.poll(() => page.getByRole('img', { name: 'Hero Product Reveal' }).evaluate((node: HTMLImageElement) => node.complete && node.naturalWidth > 0)).toBe(true)
  await page.getByLabel('Asset type').selectOption('HERO_IMAGE')
  await page.getByRole('link', { name: 'Inspect asset: Hero Product Reveal', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Hero Product Reveal' })).toBeFocused()
  await expect(page.locator('.asset-version-list').getByText('00000000-0000-4000-8000-000000000060', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit asset metadata' }).click()
  await page.getByLabel('Description').fill('Reviewed metadata; approved versions remain preserved')
  await page.getByLabel('Asset status').selectOption('NEEDS_REVIEW')
  await page.getByRole('button', { name: 'Save asset' }).click()
  await expect(page.getByText('Reviewed metadata; approved versions remain preserved')).toBeVisible()
  await expect(page.locator('.asset-version-list').getByText('00000000-0000-4000-8000-000000000061', { exact: true })).toBeVisible()
  await expect(page.getByText('Superseded', { exact: false })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('link', { name: 'Back to asset library' }).click()
  await expect(page.getByLabel('Asset type')).toHaveValue('HERO_IMAGE')
  await page.getByLabel('Asset type').selectOption('')
  await page.getByRole('button', { name: 'Create asset', exact: true }).click()
  const form = page.getByRole('form', { name: 'Create asset' })
  await form.getByLabel('Asset title').fill('Launch layout')
  await form.getByLabel('Asset type').selectOption('LAYOUT')
  await form.getByLabel('Tags', { exact: true }).fill('launch')
  await form.getByRole('button', { name: 'Save asset' }).click()
  await expect(page.getByRole('heading', { name: 'Launch layout' })).toBeVisible()
  await expect(page.getByText('No versions yet').first()).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Archive asset' }).click()
  await expect(page.getByRole('button', { name: 'Restore as draft' })).toBeVisible()
  await page.getByRole('link', { name: 'Back to asset library' }).click()
  await expect(page.getByRole('heading', { name: 'Launch layout' })).toHaveCount(0)
  await page.getByLabel('Include archived assets').check()
  await expect(page.getByRole('heading', { name: 'Launch layout' })).toBeVisible()
  await page.getByRole('link', { name: 'Inspect asset: Launch layout' }).click()
  await page.getByRole('button', { name: 'Restore as draft' }).click()
  await expect(page.getByRole('button', { name: 'Archive asset' })).toBeVisible()
})
