import { expect, test } from '@playwright/test'
const root = '/#/projects/00000000-0000-4000-8000-000000000010/collections'
test('clones exact collection pins and approves a frozen revision', async ({ page }) => {
  await page.goto(root + '/00000000-0000-4000-8000-000000000070')
  await expect(page.getByRole('heading', { name: 'Solara Launch Hero Set', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Inspect pinned version' })).toHaveCount(3)
  await page.getByRole('button', { name: 'Create draft revision', exact: true }).click()
  const draft = page.getByRole('form', { name: 'Create draft revision' })
  await draft.getByLabel('Revision change summary').fill('Review original exact pins for delivery')
  await draft.getByRole('button', { name: 'Create draft revision' }).click()
  await expect(page.getByRole('heading', { name: /Revision 2/ })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Inspect pinned version' })).toHaveCount(3)
  await expect(page.getByRole('link', { name: 'Inspect pinned version' }).first()).toHaveAttribute('href', /000000000061$/)
  await page.getByRole('button', { name: 'Edit item / replace pin' }).first().click()
  const pin = page.getByRole('form', { name: 'Edit item / replace pin' })
  await pin.getByLabel('Item note').fill('Reviewed exact hero version')
  await pin.getByRole('button', { name: 'Save item' }).click()
  await expect(page.getByText('Reviewed exact hero version', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Submit for review' }).click()
  await expect(page.getByRole('button', { name: 'Approve revision', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Edit item / replace pin' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Approve revision', exact: true }).click()
  const review = page.getByRole('form', { name: 'Approve revision' })
  await review.getByLabel('Review comment').fill('Exact delivery pins approved')
  page.once('dialog', dialog => dialog.accept())
  await review.getByRole('button', { name: 'Confirm review decision' }).click()
  await expect(page.getByText('Exact delivery pins approved', { exact: true })).toBeVisible()
  await page.getByLabel('Collection revision').selectOption('00000000-0000-4000-8000-000000000071')
  await expect(page.getByRole('heading', { name: /Revision 1.*Superseded/ })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Inspect pinned version' }).first()).toHaveAttribute('href', /000000000061$/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
