import { expect, test } from '@playwright/test'
test('overrides and supersedes human decisions while preserving original recommendation and exact pins', async ({ page }) => {
  const root = '/projects/00000000-0000-4000-8000-000000000010'
  await page.goto(`/#${root}/impact`); await page.getByRole('button', { name: 'Start assessment', exact: true }).click(); const assessment = page.getByRole('form', { name: 'Start assessment' }); await assessment.getByRole('combobox', { name: 'New direction revision' }).selectOption('00000000-0000-4000-8000-000000000041'); await assessment.getByRole('button', { name: 'Run assessment' }).click()
  const results = page.getByRole('region', { name: 'Assessment results' }); const metal = results.locator('.impact-item').filter({ has: page.getByRole('heading', { name: 'Metal Texture Detail · Version 1' }) })
  await metal.getByRole('button', { name: 'Record decision', exact: true }).click(); const form = metal.getByRole('form'); await form.getByRole('combobox', { name: 'Decision', exact: true }).selectOption('OVERRIDE'); await form.getByRole('combobox', { name: 'Replacement recommendation' }).selectOption('REVIEW_REQUIRED'); await form.getByRole('textbox', { name: 'Decision rationale' }).fill('Art director wants to review the polished material'); await form.getByRole('combobox', { name: 'Selected next action' }).fill('Review the exact version with the art director'); await form.getByRole('button', { name: 'Save decision' }).click()
  await expect(metal.getByText('Effective recommendation: Review required', { exact: true })).toBeVisible(); await expect(metal.locator('.impact-badge')).toHaveText(/Recreate candidate/); await expect(results.locator('.home-metrics dd').last()).toHaveText('3')
  await metal.getByRole('button', { name: 'Record another decision' }).click(); await metal.getByRole('form').getByRole('button', { name: 'Save decision' }).click(); await expect(metal.getByText('Effective recommendation: Recreate candidate', { exact: true })).toBeVisible()
  const history = page.getByRole('region', { name: 'Decision history' }); await expect(history.getByText('Superseded decision', { exact: true })).toBeVisible(); await history.getByRole('checkbox', { name: 'Current decisions only' }).check(); await expect(history.locator('.decision-list>li')).toHaveCount(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('link', { name: 'Project overview', exact: true }).click(); await page.getByRole('link', { name: 'View decisions' }).click(); await expect(page.getByRole('heading', { name: 'Human decisions' })).toBeVisible(); await expect(page.getByText('Art director wants to review the polished material', { exact: true })).toBeVisible()
  await page.goto(`/#${root}/assets/00000000-0000-4000-8000-000000000050/versions/00000000-0000-4000-8000-000000000061`); const version = page.getByRole('article', { name: 'Selected version: Version 2' }); await expect(version.getByText(/Solara Launch Hero Set/)).toBeVisible(); await expect(version.getByText('Approved', { exact: false }).first()).toBeVisible()
})
