import { expect, test } from '@playwright/test'

test('compares, revises, and activates exact direction versions', async ({ page }) => {
  await page.goto('/#/projects/00000000-0000-4000-8000-000000000010')
  await page.getByRole('link', { name: 'Manage directions' }).click()
  await page.getByLabel('Target revision').selectOption('00000000-0000-4000-8000-000000000041')
  await page.getByRole('button', { name: 'Compare revisions', exact: true }).click()
  await expect(page.getByText(/direction attribute groups differ/)).toBeVisible()
  await page.getByLabel('Select direction').selectOption('00000000-0000-4000-8000-000000000040')
  await page.getByRole('button', { name: 'Create direction revision', exact: true }).click()
  await page.getByLabel('Visual principles / summary').fill('Warm organic imagery with softer daylight')
  await page.getByLabel('Change summary').fill('Refine the daylight treatment')
  await page.getByRole('button', { name: 'Save direction revision', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Warm Organic · Revision 2' })).toBeVisible()
  await page.getByRole('button', { name: 'Activate selected revision' }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Activate selected revision' })).toBeFocused()
  await page.getByRole('button', { name: 'Activate selected revision' }).click()
  await dialog.getByLabel('Reason for changing the active direction').fill('Approved the warm organic revision for this campaign')
  await dialog.getByRole('button', { name: 'Confirm activation', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByText('Active direction changed.')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('link', { name: /Project overview/ }).click()
  await expect(page.getByText('Warm Organic · Revision 2')).toBeVisible()
  await expect(page.getByText('Approved the warm organic revision for this campaign')).toBeVisible()
})
