import { expect, test } from '@playwright/test'
test('assesses demo scope, filters server results and opens the exact asset version', async ({ page }) => {
  await page.goto('/#/projects/00000000-0000-4000-8000-000000000010/impact')
  await page.getByRole('button', { name: 'Start assessment', exact: true }).click()
  const form = page.getByRole('form', { name: 'Start assessment' })
  await form.getByLabel('New direction revision').selectOption('00000000-0000-4000-8000-000000000041')
  await form.getByRole('button', { name: 'Run assessment' }).click()
  const results = page.getByRole('region', { name: 'Assessment results' })
  await expect(results.getByText('These are recommendations, not an objective quality judgment. A person decides.')).toBeVisible()
  await expect(results.getByText('No images were inspected.')).toBeVisible()
  await expect(results.getByText('Simulated', { exact: true })).toBeVisible()
  await expect(results.locator('.impact-item')).toHaveCount(4)
  await expect(results.locator('.impact-item').first().getByRole('heading', { name: 'Factory Background · Version 1' })).toBeVisible()
  await results.getByRole('combobox', { name: 'Recommendation', exact: true }).selectOption('REVIEW_REQUIRED')
  await expect(results.locator('.impact-item')).toHaveCount(1)
  await expect(results.locator('.home-metrics dd').first()).toHaveText('4')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await results.getByRole('link', { name: 'Inspect exact asset version' }).click()
  await expect(page).toHaveURL(/\/versions\/00000000-0000-4000-8000-000000000063$/)
  await expect(page.getByRole('article', { name: 'Selected version: Version 1' }).getByText('00000000-0000-4000-8000-000000000063', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Project overview' }).click()
  await expect(page.locator('.home-metrics').getByText('4', { exact: true }).last()).toBeVisible()
  await expect(page.getByText('Completed', { exact: false })).toBeVisible()
})
