import { expect, test } from '@playwright/test'
test('registers, annotates, links an exact asset version, edits and archives a reference', async ({ page }) => {
  await page.goto('/#/projects/00000000-0000-4000-8000-000000000010')
  await page.getByRole('link', { name: 'View references' }).click()
  await expect(page.getByText('Brushed steel macro')).toBeVisible()
  const image = page.getByRole('img', { name: 'Brushed steel macro' })
  await expect.poll(() => image.evaluate((node: HTMLImageElement) => node.complete && node.naturalWidth > 0)).toBe(true)
  await page.getByRole('button', { name: 'Register reference', exact: true }).click()
  await page.getByLabel('Reference title').fill('Campaign material reference')
  await page.getByLabel('Source URL').fill('https://example.com/texture')
  await page.getByLabel('Usage rights / permission notes').fill('Permission requested; do not publish yet')
  await page.getByRole('button', { name: 'Save reference', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Campaign material reference' })).toBeVisible()
  await page.getByRole('button', { name: 'Add attribute', exact: true }).click()
  await page.getByLabel('Attribute category').selectOption('MATERIAL')
  await page.getByLabel('Attribute value').fill('Brushed aluminum')
  await page.getByRole('button', { name: 'Save attribute' }).click()
  await expect(page.getByText('Brushed aluminum')).toBeVisible()
  await expect(page.getByText(/User-provided.*Confirmed/)).toBeVisible()
  await page.getByLabel('Link target').selectOption('ASSET_VERSION:00000000-0000-4000-8000-000000000060')
  await page.getByLabel('How this reference informs the item').fill('Original hero material study')
  await page.getByRole('button', { name: 'Link reference', exact: true }).click()
  await expect(page.getByText('Hero Product Reveal · Version 1', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit metadata', exact: true }).click()
  await page.getByLabel('Reference title').fill('Reviewed campaign reference')
  await page.getByRole('button', { name: 'Save reference', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Reviewed campaign reference' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Archive reference' }).click()
  await expect(page.getByRole('button', { name: 'Restore reference' })).toBeVisible()
  await page.getByRole('button', { name: 'Back to reference board' }).click()
  await expect(page.getByRole('heading', { name: 'Reviewed campaign reference' })).toHaveCount(0)
  await page.getByLabel('Include archived references').check()
  await expect(page.getByRole('heading', { name: 'Reviewed campaign reference' })).toBeVisible()
})
