import { expect, test } from '@playwright/test'
test('compares versions and creates a derived version while preserving the approved pin', async ({ page }) => {
  await page.goto('/#/projects/00000000-0000-4000-8000-000000000010/assets/00000000-0000-4000-8000-000000000050')
  await expect(page.getByRole('article', { name: 'Selected version: Version 2' })).toBeVisible()
  await page.getByLabel('Second version').selectOption('00000000-0000-4000-8000-000000000060')
  await page.getByRole('button', { name: 'Compare versions' }).click()
  await expect(page.getByRole('article', { name: 'First version: Version 2' })).toBeVisible()
  await expect(page.getByRole('article', { name: 'Second version: Version 1' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Create new version', exact: true }).click()
  const form = page.getByRole('form', { name: 'Create new version' })
  await expect(page.getByRole('button', { name: 'Edit asset metadata' })).toBeDisabled()
  await expect(form.getByLabel('Revision rationale')).toBeFocused()
  await form.getByLabel('Revision rationale').fill('Refine hero for warm organic campaign')
  await form.getByLabel('Direction revision').selectOption('00000000-0000-4000-8000-000000000041')
  await form.getByLabel('Prompt', { exact: true }).fill('Soft natural light and warm material accents')
  await form.getByLabel('Mood', { exact: true }).fill('calm\ncrafted')
  await form.getByLabel('File source').selectOption('external')
  await form.getByLabel('File URL', { exact: true }).fill('/demo-assets/hero-v2.jpg')
  await form.getByLabel('MIME type').fill('image/jpeg')
  await form.getByLabel('Brushed steel macro', { exact: true }).check()
  await form.getByLabel('Reference usage note: Brushed steel macro').fill('Retain the product material proportions')
  await form.getByRole('button', { name: 'Save new version' }).click()
  const next = page.getByRole('article', { name: 'Selected version: Version 3' })
  await expect(next).toBeVisible()
  await expect(next.getByText('This version has no recorded collection pins.')).toBeVisible()
  await expect(next.getByText('Soft natural light and warm material accents')).toBeVisible()
  await expect(next.getByText('Warm Organic · Revision 1', { exact: true })).toBeVisible()
  await expect.poll(() => next.getByRole('img').evaluate((node: HTMLImageElement) => node.complete && node.naturalWidth > 0)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByLabel('Inspect version').selectOption('00000000-0000-4000-8000-000000000061')
  const old = page.getByRole('article', { name: 'Selected version: Version 2' })
  await expect(old.getByText(/Solara Launch Hero Set/)).toBeVisible()
  await expect(old.getByText('Historical version', { exact: false })).toBeVisible()
  await expect(old.getByText('Approved', { exact: false }).first()).toBeVisible()
  await expect(old.getByRole('button', { name: 'Version 3' })).toBeVisible()
})
