export const directionCopy = {
  heading: 'Creative directions', back: 'Project overview', loading: 'Loading directions…', empty: 'No creative directions yet.',
  create: 'Create direction', clone: 'Clone selected revision', revise: 'Create direction revision',
  name: 'Direction name', description: 'Description', summary: 'Visual principles / summary',
  palette: 'Palette', colorName: 'Color name', hex: 'Hex color (optional)', colorRole: 'Color role (optional)', addColor: 'Add color', remove: 'Remove',
  quality: 'Lighting quality', direction: 'Lighting direction', temperature: 'Lighting temperature', lightingNotes: 'Lighting notes',
  framing: 'Composition framing', layout: 'Composition layout', compositionNotes: 'Composition notes',
  materials: 'Materials', mood: 'Mood', families: 'Typography families', typographyNotes: 'Typography notes', stylePrompt: 'Style prompt', changeSummary: 'Change summary',
  requiredAttributes: 'Required attributes', forbiddenAttributes: 'Forbidden attributes', label: 'Attribute label', value: 'Attribute value', category: 'Category', hard: 'Hard constraint', addAttribute: 'Add attribute',
  categories: { PALETTE: 'Palette', LIGHTING: 'Lighting', COMPOSITION: 'Composition', MATERIAL: 'Material', MOOD: 'Mood', TYPOGRAPHY: 'Typography', SUBJECT: 'Subject', OTHER: 'Other' },
  lines: 'Enter one item per line.', save: 'Save direction', saveRevision: 'Save direction revision', saving: 'Saving…', cancel: 'Cancel',
  statuses: { DRAFT: 'Draft', ACTIVE: 'Active', SUPERSEDED: 'Superseded', ARCHIVED: 'Archived' }, unknown: 'Unknown status', revision: 'Revision', selectDirection: 'Select direction', selectRevision: 'Select revision',
  branchStatus: 'Direction status', diffNote: 'Deterministic attribute comparison. No AI call is made.', guideline: 'Guideline', otherAttributes: 'Other attributes',
  activeRevision: 'Active project revision', none: 'Not recorded', compare: 'Compare revisions', from: 'Previous revision', to: 'Target revision', comparison: 'Direction comparison', noFrom: 'No previous revision',
  before: 'Before', after: 'After', noChange: 'No recorded changes.',
  activate: 'Activate selected revision', confirm: 'Confirm activation', reason: 'Reason for changing the active direction',
  activationNote: 'This changes the project’s active direction. Existing asset versions, collection pins, briefs, and past assessments remain unchanged.',
  immutable: 'New revisions preserve the previous attributes. Saving a revision does not activate it.',
  saved: 'Direction saved.', activated: 'Active direction changed.', role: 'Your role can view directions but cannot change them.', retry: 'Try again', requestId: 'Request ID',
  invalid: 'Check the highlighted fields.', required: 'This field is required.', reasonError: 'Enter a reason between 3 and 1000 characters.',
  uncertain: 'Check the direction history before retrying a failed write; this endpoint does not support idempotency.',
} as const
