import { useEffect, useRef, useState } from 'react'
import { DirectionRevisionInputSchema, type DirectionRevisionInput } from '../../../packages/contracts/src'
import { ApiClientError } from '../../lib/api/client'
import { directionCopy as c } from './copy'

const emptyDirection: DirectionRevisionInput = { summary: '', palette: [], lighting: { quality: null, direction: null, temperature: null, notes: null }, composition: { framing: null, layout: null, notes: null }, materials: [], mood: [], typography: { families: [], notes: null }, requiredAttributes: [], forbiddenAttributes: [], stylePrompt: null, changeSummary: null }
export function DirectionForm({ initial = emptyDirection, initialName = '', revisionMode, save, cancel }: { initial?: DirectionRevisionInput; initialName?: string; revisionMode: boolean; save: (name: string, description: string, revision: DirectionRevisionInput) => Promise<void>; cancel: () => void }) {
  const [input, setInput] = useState(() => structuredClone(initial))
  const [name, setName] = useState(initialName)
  const [description, setDescription] = useState('')
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [error, setError] = useState<ApiClientError | null>(null)
  const [saving, setSaving] = useState(false); const busy = useRef(false); const summary = useRef<HTMLDivElement>(null)
  const form = useRef<HTMLFormElement>(null)
  useEffect(() => { form.current?.querySelector<HTMLElement>('input,textarea')?.focus() }, [])
  const normalize = (value: string) => value || null
  function textField(path: string, label: string, value: string | null, set: (value: string) => void, multiline = false) { const props = { id: `direction-${path}`, value: value ?? '', onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => set(event.target.value), 'aria-invalid': Boolean(errors[path]), 'aria-describedby': `error-${path}` }; return <div className="direction-field" key={path}><label htmlFor={props.id}>{label}</label>{multiline ? <textarea {...props} /> : <input {...props} />}<p className="field-error" id={`error-${path}`}>{errors[path]}</p></div> }
  async function submit(event: React.FormEvent) {
    event.preventDefault(); if (busy.current) return
    const issues: Record<string, string> = {}
    if (!revisionMode && (!name.trim() || name.trim().length > 160)) issues.name = c.required
    if (!input.summary.trim()) issues.summary = c.required
    if (revisionMode && !input.changeSummary?.trim()) issues.changeSummary = c.required
    input.palette.forEach((color, index) => { if (!color.name.trim()) issues[`palette.${index}.name`] = c.required })
    for (const group of ['requiredAttributes', 'forbiddenAttributes'] as const) input[group].forEach((value, index) => { if (!value.label.trim()) issues[`${group}.${index}.label`] = c.required; if (!value.value.trim()) issues[`${group}.${index}.value`] = c.required })
    const tokens = (values: string[]) => values.map(value => value.trim()).filter(Boolean)
    const parsed = DirectionRevisionInputSchema.safeParse({ ...input, summary: input.summary.trim(), materials: tokens(input.materials), mood: tokens(input.mood), typography: { ...input.typography, families: tokens(input.typography.families) }, changeSummary: input.changeSummary?.trim() || null, stylePrompt: input.stylePrompt?.trim() || null })
    if (!parsed.success) for (const issue of parsed.error.issues) issues[issue.path.join('.')] = issue.message
    if (Object.keys(issues).length || !parsed.success) { setErrors(issues); queueMicrotask(() => summary.current?.focus()); return }
    busy.current = true; setSaving(true); setError(null); setErrors({})
    try { await save(name.trim(), description.trim(), parsed.data) } catch (value) { const failure = value instanceof ApiClientError ? value : new ApiClientError('Unable to save direction.', { code: 'UNKNOWN' }); setError(failure); setErrors(Object.fromEntries(failure.details.map(detail => [detail.path.replace(/^body\.(revision\.)?/, ''), detail.message]))); queueMicrotask(() => summary.current?.focus()) } finally { setSaving(false); busy.current = false }
  }
  return <form ref={form} className="direction-form" aria-label={revisionMode ? c.revise : c.create} onSubmit={submit}><h3>{revisionMode ? c.revise : c.create}</h3><p>{c.immutable}</p>{(error || Object.keys(errors).length > 0) && <div ref={summary} tabIndex={-1} role="alert" className="project-error"><p>{error?.message ?? c.invalid}</p>{Object.entries(errors).map(([path, message]) => <p key={path}>{path}: {message}</p>)}{error?.requestId && <p>{c.requestId}: <code>{error.requestId}</code></p>}{error && <p>{c.uncertain}</p>}</div>}
    <fieldset disabled={saving}><legend className="sr-only">{c.heading}</legend>
    {!revisionMode && <>{textField('name', c.name, name, setName)}{textField('description', c.description, description, setDescription)}</>}
    {textField('summary', c.summary, input.summary, value => setInput(previous => ({ ...previous, summary: value })), true)}
    <fieldset className="direction-group"><legend>{c.palette}</legend>{input.palette.map((color, index) => <div key={index} className="palette-row">{(['name', 'hex', 'role'] as const).map(field => textField(`palette.${index}.${field}`, field === 'name' ? c.colorName : field === 'hex' ? c.hex : c.colorRole, color[field], value => setInput(previous => ({ ...previous, palette: previous.palette.map((item, i) => i === index ? { ...item, [field]: field === 'name' ? value : normalize(value) } : item) }))))}<button type="button" onClick={() => setInput(previous => ({ ...previous, palette: previous.palette.filter((_, i) => i !== index) }))}>{c.remove}</button></div>)}<button type="button" onClick={() => setInput(previous => ({ ...previous, palette: [...previous.palette, { name: '', hex: null, role: null }] }))}>{c.addColor}</button></fieldset>
    {(['quality', 'direction', 'temperature', 'notes'] as const).map(field => textField(`lighting.${field}`, field === 'notes' ? c.lightingNotes : c[field], input.lighting[field], value => setInput(previous => ({ ...previous, lighting: { ...previous.lighting, [field]: normalize(value) } }))))}
    {(['framing', 'layout', 'notes'] as const).map(field => textField(`composition.${field}`, field === 'notes' ? c.compositionNotes : c[field], input.composition[field], value => setInput(previous => ({ ...previous, composition: { ...previous.composition, [field]: normalize(value) } }))))}
    {(['materials', 'mood'] as const).map(field => textField(field, c[field], input[field].join('\n'), value => setInput(previous => ({ ...previous, [field]: value.split('\n') })), true))}<p className="note">{c.lines}</p>
    {textField('typography.families', c.families, input.typography.families.join('\n'), value => setInput(previous => ({ ...previous, typography: { ...previous.typography, families: value.split('\n') } })), true)}{textField('typography.notes', c.typographyNotes, input.typography.notes, value => setInput(previous => ({ ...previous, typography: { ...previous.typography, notes: normalize(value) } })))}
    {(['requiredAttributes', 'forbiddenAttributes'] as const).map(group => <fieldset className="direction-group" key={group}><legend>{c[group]}</legend>{input[group].map((attribute, index) => <div key={attribute.id} className="attribute-row">{(['label', 'value'] as const).map(field => textField(`${group}.${index}.${field}`, c[field], attribute[field], value => setInput(previous => ({ ...previous, [group]: previous[group].map(item => item.id === attribute.id ? { ...item, [field]: value } : item) }))))}<label htmlFor={`category-${attribute.id}`}>{c.category}</label><select id={`category-${attribute.id}`} value={attribute.category} onChange={event => { const category = event.target.value as typeof attribute.category; setInput(previous => ({ ...previous, [group]: previous[group].map(item => item.id === attribute.id ? { ...item, category } : item) })) }}>{Object.entries(c.categories).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><label className="attribute-checkbox"><input type="checkbox" checked={attribute.hard} onChange={event => setInput(previous => ({ ...previous, [group]: previous[group].map(item => item.id === attribute.id ? { ...item, hard: event.target.checked } : item) }))} />{c.hard}</label><button type="button" onClick={() => setInput(previous => ({ ...previous, [group]: previous[group].filter(item => item.id !== attribute.id) }))}>{c.remove}</button></div>)}<button type="button" onClick={() => setInput(previous => ({ ...previous, [group]: [...previous[group], { id: crypto.randomUUID(), category: 'OTHER', label: '', value: '', hard: false }] }))}>{c.addAttribute} · {c[group]}</button></fieldset>)}
    {textField('stylePrompt', c.stylePrompt, input.stylePrompt, value => setInput(previous => ({ ...previous, stylePrompt: normalize(value) })), true)}{textField('changeSummary', c.changeSummary, input.changeSummary, value => setInput(previous => ({ ...previous, changeSummary: normalize(value) })), true)}
    <div className="project-actions"><button type="submit">{saving ? c.saving : revisionMode ? c.saveRevision : c.save}</button><button type="button" onClick={cancel}>{c.cancel}</button></div></fieldset></form>
}
