import { useRef, useState } from 'react'
import { AttributeCategorySchema, type AttributeCategory } from '../../../packages/contracts/src'
import { ApiClientError } from '../../lib/api/client'
import type { ReferenceView } from './api'
import { referenceCopy as c } from './copy'
export function AttributeForm({ attribute, save, cancel }: { attribute?: ReferenceView['attributes'][number]; save: (category: AttributeCategory, value: { text: string; hex: string | null }, status: 'CONFIRMED' | 'CORRECTED' | 'REJECTED') => Promise<void>; cancel: () => void }) {
  const [category, setCategory] = useState<AttributeCategory>('OTHER'); const [text, setText] = useState(attribute?.value.text ?? ''); const [hex, setHex] = useState(attribute?.value.hex ?? ''); const [status, setStatus] = useState<'CONFIRMED' | 'CORRECTED' | 'REJECTED'>('CORRECTED'); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const busy = useRef(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); if (busy.current) return; if (!text.trim() || (hex && !/^#[a-f\d]{6}$/i.test(hex))) { setError(!text.trim() ? c.required : c.invalidHex); return } busy.current = true; setSaving(true); setError(''); try { await save(category, { text: text.trim(), hex: hex || null }, status) } catch (value) { setError(value instanceof ApiClientError ? [value.message, ...value.details.map(item => item.message), value.requestId ? c.requestId + ': ' + value.requestId : '', c.uncertain].filter(Boolean).join(' · ') : value instanceof Error ? value.message : c.validation) } finally { busy.current = false; setSaving(false) } }
  return <form className="reference-form" aria-label={attribute ? c.review : c.addAttribute} onSubmit={submit}><h4>{attribute ? c.review : c.addAttribute}</h4>{error && <p role="alert">{error}</p>}<fieldset disabled={saving}><legend className="sr-only">{c.attributes}</legend>{!attribute && <label>{c.category}<select value={category} onChange={event => setCategory(AttributeCategorySchema.parse(event.target.value))}>{Object.entries(c.categories).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>}<label>{c.value}<textarea autoFocus value={text} onChange={event => setText(event.target.value)} /></label><label>{c.hex}<input value={hex} onChange={event => setHex(event.target.value)} /></label>{attribute && <label>{c.reviewStatus}<select value={status} onChange={event => { const value = event.target.value; if (value === 'CONFIRMED' || value === 'CORRECTED' || value === 'REJECTED') setStatus(value) }}><option value="CONFIRMED">{c.reviews.CONFIRMED}</option><option value="CORRECTED">{c.reviews.CORRECTED}</option><option value="REJECTED">{c.reviews.REJECTED}</option></select></label>}<div className="project-actions"><button>{saving ? c.saving : c.saveAttribute}</button><button type="button" onClick={cancel}>{c.cancel}</button></div></fieldset></form>
}
