export const referenceCopy = {
  heading: 'Reference Board', back: 'Project overview', create: 'Register reference', edit: 'Edit metadata',
  title: 'Reference title', description: 'Description / notes', sourceUrl: 'Source URL', rights: 'Usage rights / permission notes', tags: 'Tags', tagsHelp: 'Enter one tag per line.',
  urlNote: 'Register an HTTP(S) source URL. Remote pages and images are not automatically fetched. File uploads and AI analysis are not available yet.',
  save: 'Save reference', saving: 'Saving…', cancel: 'Cancel', loading: 'Loading references…', retry: 'Try again', requestId: 'Request ID',
  empty: 'No references yet. Register a source to start your reference board.', noResults: 'No references match these filters.', search: 'Search references', source: 'Source type', all: 'All sources', category: 'Attribute category', allCategories: 'All categories', tag: 'Filter by tag', includeArchived: 'Include archived references', more: 'Load more references',
  sources: { USER_UPLOAD: 'User upload', PUBLIC_URL: 'Public URL', INTERNAL_ASSET: 'Internal asset', DEMO_ASSET: 'Demo sample' },
  categories: { PALETTE: 'Palette', LIGHTING: 'Lighting', COMPOSITION: 'Composition', MATERIAL: 'Material', MOOD: 'Mood', TYPOGRAPHY: 'Typography', SUBJECT: 'Subject', OTHER: 'Other' },
  origins: { USER_PROVIDED: 'User-provided', AI_INFERRED: 'AI-inferred', SYSTEM_DERIVED: 'System-derived' },
  reviews: { UNREVIEWED: 'Unreviewed', CONFIRMED: 'Confirmed', CORRECTED: 'Corrected', REJECTED: 'Rejected' },
  targets: { DIRECTION_REVISION: 'Direction revision', ASSET: 'Asset', ASSET_VERSION: 'Asset version' },
  unknown: 'Unknown', noRights: 'No usage rights recorded. Confirm permission before reuse.', noImage: 'No preview available', brokenImage: 'Preview could not be loaded', sourceLink: 'Open source', sourceUnavailable: 'Source URL unavailable', inspect: 'Inspect reference', close: 'Back to reference board',
  attributes: 'Visual attributes', noAttributes: 'No attributes recorded.', addAttribute: 'Add attribute', value: 'Attribute value', hex: 'Hex color (optional)', review: 'Review / correct attribute', saveAttribute: 'Save attribute', reviewStatus: 'Review status', origin: 'Origin',
  links: 'Linked project items', noLinks: 'No linked items yet.', link: 'Link reference', target: 'Link target', usageNote: 'How this reference informs the item', relationship: 'Relationship type', unlink: 'Remove link', unavailable: 'Linked item unavailable',
  archive: 'Archive reference', restore: 'Restore reference', archiveConfirm: 'Archive this reference? Its metadata and links will remain preserved.', archived: 'Archived',
  saved: 'Reference saved.', updated: 'Reference updated.', readOnly: 'Your role can inspect references but cannot change them.',
  required: 'This field is required.', invalidUrl: 'Enter a valid HTTP(S) URL.', invalidHex: 'Use a hex color such as #AABBCC.', validation: 'Check the fields below.',
  conflict: 'The server has a newer copy. Load it for comparison; your draft stays in the form.', reload: 'Load latest metadata', latest: 'Latest server metadata', uncertain: 'Check the reference board before retrying a failed write; this endpoint has no idempotency support.',
} as const
