import { useRef, useState } from 'react'
import { ApiClientError } from '../../lib/api/client'
import type { LinkTarget, ReferenceView, referenceApi } from './api'
import { ReferenceForm } from './ReferenceForm'
import { AttributeForm } from './AttributeForm'
import { ReferencePreview } from './SafeMedia'
import { label, safeUrl } from './display'
import { referenceCopy as c } from './copy'
export function ReferenceDetail({ reference: ref, api, targets, canEdit, updated, close }: { reference: ReferenceView; api: ReturnType<typeof referenceApi>; targets: LinkTarget[]; canEdit: boolean; updated: (ref: ReferenceView) => void; close: () => void }) {
  const [edit, setEdit] = useState(false); const [attribute, setAttribute] = useState<ReferenceView['attributes'][number] | 'new' | null>(null); const [target, setTarget] = useState(''); const [usage, setUsage] = useState(''); const [relationship, setRelationship] = useState('INSPIRATION'); const [error, setError] = useState<ApiClientError | null>(null); const [pending, setPending] = useState(false); const busy = useRef(false)
  async function mutate(action: () => Promise<ReferenceView>) { if (busy.current) return; busy.current = true; setPending(true); setError(null); try { updated(await action()) } catch (value) { setError(value instanceof ApiClientError ? value : new ApiClientError('Unable to update reference.', { code: 'UNKNOWN' })) } finally { busy.current = false; setPending(false) } }
  async function saveAttribute(category: Parameters<typeof api.addAttribute>[1], value: { text: string; hex: string | null }, status: 'CONFIRMED' | 'CORRECTED' | 'REJECTED') {
    if (attribute && attribute !== 'new') await api.reviewAttribute(attribute.id, value, status); else await api.addAttribute(ref.id, category, value.text, value.hex)
    setAttribute(null)
    // The write is confirmed; a read failure must never offer to repeat it.
    await mutate(async () => (await api.get(ref.id)).data)
  }
  const href = safeUrl(ref.sourceUrl)
  return <article className="reference-detail"><button disabled={pending || edit || Boolean(attribute)} onClick={close}>{c.close}</button><h3 tabIndex={-1}>{ref.title}</h3><ReferencePreview key={ref.thumbnailUrl} url={ref.thumbnailUrl ?? ref.fileUrl} title={ref.title} /><p>{ref.description}</p><p>{label(c.sources, ref.sourceType)} {ref.archivedAt && <strong> · {c.archived}</strong>}</p><p className="reference-rights"><strong>{c.rights}</strong><br />{ref.usageRightsNote ?? c.noRights}</p><p>{ref.tags.join(' · ')}</p>{href ? <a href={href} target="_blank" rel="noopener noreferrer">{c.sourceLink}</a> : <p>{c.sourceUnavailable}</p>}
    {error && <div role="alert" className="project-error"><p>{error.message}</p>{error.requestId && <p>{c.requestId}: {error.requestId}</p>}<p>{c.uncertain}</p><button disabled={pending || edit || Boolean(attribute)} onClick={() => void mutate(async () => (await api.get(ref.id)).data)}>{c.reload}</button></div>}
    {canEdit && <div className="project-actions"><button disabled={pending || edit || Boolean(attribute)} onClick={() => { setEdit(true); setAttribute(null) }}>{c.edit}</button><button disabled={pending || edit || Boolean(attribute)} onClick={() => { if (ref.archivedAt || window.confirm(c.archiveConfirm)) void mutate(async () => (await api.archive(ref, !ref.archivedAt)).data) }}>{ref.archivedAt ? c.restore : c.archive}</button></div>}
    {edit && <ReferenceForm reference={ref} reload={async () => (await api.get(ref.id)).data} cancel={() => setEdit(false)} save={async input => { if ('expectedUpdatedAt' in input) { const result = await api.edit(ref.id, input); updated(result.data); setEdit(false) } }} />}
    <section><h4>{c.attributes}</h4>{!ref.attributes.length && <p>{c.noAttributes}</p>}<ul className="reference-attributes">{ref.attributes.map(item => <li key={item.id}><strong>{label(c.categories, item.attributeType)}</strong><p>{item.value.text} {item.value.hex}</p><p>{c.origin}: {label(c.origins, item.origin)} · {label(c.reviews, item.reviewStatus)}</p>{canEdit && <button disabled={pending || edit || Boolean(attribute)} onClick={() => { setAttribute(item); setEdit(false) }}>{c.review}</button>}</li>)}</ul>{canEdit && <button disabled={pending || edit || Boolean(attribute)} onClick={() => { setAttribute('new'); setEdit(false) }}>{c.addAttribute}</button>}{attribute && <AttributeForm key={attribute === 'new' ? 'new' : attribute.id} attribute={attribute === 'new' ? undefined : attribute} save={saveAttribute} cancel={() => setAttribute(null)} />}</section>
    <section><h4>{c.links}</h4>{!ref.links.length && <p>{c.noLinks}</p>}<ul className="reference-attributes">{ref.links.map((item, index) => <li key={`${item.targetType}:${item.targetId}:${index}`}><strong>{label(c.targets, item.targetType)}</strong><p>{targets.find(target => target.id === item.targetId && target.type === item.targetType)?.label ?? c.unavailable}</p><code>{item.targetId}</code><p>{item.relationshipType} {item.usageNote}</p>{canEdit && <button disabled={pending || edit || Boolean(attribute)} onClick={() => void mutate(async () => (await api.unlink(ref.id, item.targetType, item.targetId)).data)}>{c.unlink}</button>}</li>)}</ul>{canEdit && <form className="reference-form" aria-label={c.link} onSubmit={event => { event.preventDefault(); const item = targets.find(item => `${item.type}:${item.id}` === target); if (item) void mutate(async () => (await api.link(ref.id, { targetType: item.type, targetId: item.id, usageNote: usage.trim() || null, relationshipType: item.type === 'ASSET' ? relationship.trim() || 'INSPIRATION' : null })).data) }}><fieldset disabled={pending || edit || Boolean(attribute)}><legend>{c.link}</legend><label>{c.target}<select required value={target} onChange={event => setTarget(event.target.value)}><option value="">Choose a project item</option>{targets.map(item => <option key={`${item.type}:${item.id}`} value={`${item.type}:${item.id}`}>{label(c.targets, item.type)}: {item.label}</option>)}</select></label>{target.startsWith('ASSET:') && <label>{c.relationship}<input value={relationship} onChange={event => setRelationship(event.target.value)} /></label>}<label>{c.usageNote}<textarea value={usage} onChange={event => setUsage(event.target.value)} /></label><button disabled={!target}>{pending ? c.saving : c.link}</button></fieldset></form>}</section>
  </article>
}
