import { useEffect, useMemo, useRef, useState } from 'react'
import type { ApiClient } from '../../lib/api/client'
import { ApiClientError } from '../../lib/api/client'
import { projectApi, type ProjectView } from '../projects/api'
import { referenceApi, type LinkTarget, type ReferenceView } from './api'
import { ReferenceForm } from './ReferenceForm'
import { ReferenceDetail } from './ReferenceDetail'
import { label } from './display'
import { ReferencePreview } from './SafeMedia'
import { referenceCopy as c } from './copy'
import './references.css'
export function ReferenceBoard({ client, projectId }: { client: ApiClient; projectId: string }) {
  const api = useMemo(() => referenceApi(client), [client]); const projects = useMemo(() => projectApi(client), [client])
  const [project, setProject] = useState<ProjectView | null>(null); const [targets, setTargets] = useState<LinkTarget[]>([]); const [items, setItems] = useState<ReferenceView[]>([]); const [selected, setSelected] = useState<ReferenceView | null>(null); const [create, setCreate] = useState(false); const [q, setQ] = useState(''); const [tag, setTag] = useState(''); const [sourceType, setSource] = useState(''); const [attributeType, setCategory] = useState(''); const [includeArchived, setArchived] = useState(false); const [cursor, setCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [moreLoading, setMoreLoading] = useState(false); const [error, setError] = useState<ApiClientError | null>(null); const [attempt, setAttempt] = useState(0); const [notice, setNotice] = useState(''); const generation = useRef(0); const paging = useRef(false); const opening = useRef(0); const heading = useRef<HTMLHeadingElement>(null)
  const query = useMemo(() => ({ q, tag: tag || undefined, sourceType: sourceType || undefined, attributeType: attributeType || undefined, includeArchived }), [q, tag, sourceType, attributeType, includeArchived])
  useEffect(() => { const controller = new AbortController(); Promise.all([projects.get(projectId, controller.signal), api.targets(projectId, controller.signal)]).then(([project, targets]) => { if (!controller.signal.aborted) { setProject(project.data); setTargets(targets) } }).catch(value => { if (!controller.signal.aborted) setError(asError(value)) }); return () => controller.abort() }, [projects, api, projectId, attempt])
  useEffect(() => { const controller = new AbortController(); const current = ++generation.current; paging.current = false
    // oxlint-disable-next-line react/set-state-in-effect -- Synchronize list state with server filters.
    setLoading(true); setError(null); setMoreLoading(false)
    api.list(projectId, query, controller.signal).then(result => { if (!controller.signal.aborted && generation.current === current) { setItems(result.data); setCursor(result.page.nextCursor); setLoading(false) } }).catch(value => { if (!controller.signal.aborted) { setError(asError(value)); setLoading(false) } }); return () => controller.abort()
  }, [api, projectId, query, attempt])
  useEffect(() => { heading.current?.focus() }, [selected])
  async function more() { if (!cursor || paging.current) return; paging.current = true; setMoreLoading(true); const current = generation.current; try { const result = await api.list(projectId, { ...query, cursor }); if (current === generation.current) { setItems(previous => [...previous, ...result.data]); setCursor(result.page.nextCursor) } } catch (value) { if (current === generation.current) setError(asError(value)) } finally { if (current === generation.current) { paging.current = false; setMoreLoading(false) } } }
  async function inspect(id: string) { const current = ++opening.current; setNotice(c.loading); try { const result = await api.get(id); if (current === opening.current) { setSelected(result.data); setCreate(false); setNotice('') } } catch (value) { if (current === opening.current) { setError(asError(value)); setNotice('') } } }
  const canEdit = Boolean(project && ['OWNER', 'EDITOR', 'REVIEWER'].includes(project.currentUserRole))
  function updated(value: ReferenceView) { setSelected(value); setNotice(c.updated); setAttempt(previous => previous + 1) }
  return <><nav><a href={`#/projects/${projectId}`}>{c.back}</a></nav><div className="projects-heading"><div><h2 ref={heading} tabIndex={-1}>{c.heading}</h2><p>{project?.name}</p></div>{canEdit && !selected && <button onClick={() => setCreate(true)}>{c.create}</button>}</div>{notice && <p role="status">{notice}</p>}{project && !canEdit && <p>{c.readOnly}</p>}{error && <div className="project-error" role="alert"><p>{error.message}</p>{error.requestId && <p>{c.requestId}: {error.requestId}</p>}<button onClick={() => setAttempt(value => value + 1)}>{c.retry}</button></div>}
    {selected ? <ReferenceDetail key={selected.id} reference={selected} api={api} targets={targets} canEdit={canEdit} updated={updated} close={() => { setSelected(null); setNotice('') }} /> : <>{create && <ReferenceForm cancel={() => setCreate(false)} save={async input => { if ('sourceType' in input) { const result = await api.create(projectId, input); setCreate(false); setSelected(result.data); setNotice(c.saved); setAttempt(value => value + 1) } }} />}<div className="project-filters"><label>{c.search}<input type="search" value={q} onChange={event => setQ(event.target.value)} /></label><label>{c.tag}<input value={tag} onChange={event => setTag(event.target.value)} /></label><label>{c.source}<select value={sourceType} onChange={event => setSource(event.target.value)}><option value="">{c.all}</option>{Object.entries(c.sources).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>{c.category}<select value={attributeType} onChange={event => setCategory(event.target.value)}><option value="">{c.allCategories}</option>{Object.entries(c.categories).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="reference-checkbox"><input type="checkbox" checked={includeArchived} onChange={event => setArchived(event.target.checked)} />{c.includeArchived}</label></div>{loading ? <p role="status">{c.loading}</p> : <>{!error && !items.length && <p role="status">{q || tag || sourceType || attributeType ? c.noResults : c.empty}</p>}<ul className="reference-grid">{items.map(item => <li className="reference-card" key={item.id}><ReferencePreview key={item.thumbnailUrl} url={item.thumbnailUrl ?? item.fileUrl} title={item.title} /><div className="reference-card-body"><p className="eyebrow">{label(c.sources, item.sourceType)} {item.archivedAt && ` · ${c.archived}`}</p><h3>{item.title}</h3><p>{item.description}</p><p>{item.tags.join(' · ')}</p><p className="reference-rights"><strong>{c.rights}</strong><br />{item.usageRightsNote ?? c.noRights}</p><button onClick={() => void inspect(item.id)} aria-label={`${c.inspect}: ${item.title}`}>{c.inspect}</button></div></li>)}</ul>{cursor && <button disabled={moreLoading} onClick={() => void more()}>{moreLoading ? c.loading : c.more}</button>}</>}</>}
  </>
}
function asError(value: unknown) { return value instanceof ApiClientError ? value : new ApiClientError('Unable to load references.', { code: 'UNKNOWN' }) }
