export const assetCopy = {
  heading: 'Asset Library', overview: 'Project overview', references: 'Reference board', create: 'Create asset', edit: 'Edit asset metadata', save: 'Save asset', saving: 'Saving…', cancel: 'Cancel', title: 'Asset title', description: 'Description', type: 'Asset type', tags: 'Tags', tagHelp: 'Enter one tag per line.', owner: 'Owner', unassigned: 'Unassigned', preserveOwner: 'Keep current owner', createNote: 'Create a logical asset record. Files and new versions are added in the next feature; this form creates no version.',
  search: 'Search assets', status: 'Asset status', allStatuses: 'All statuses', allTypes: 'All asset types', direction: 'Latest version direction', allDirections: 'All directions', tag: 'Filter by tag', allOwners: 'All owners', includeArchived: 'Include archived assets', sort: 'Sort assets', sorts: { 'updatedAt:desc': 'Recently updated', 'title:asc': 'Title A–Z', 'status:asc': 'Status A–Z', 'versionCount:desc': 'Most versions' },
  types: { HERO_IMAGE: 'Hero image', PRODUCT_IMAGE: 'Product image', BACKGROUND: 'Background', TEXTURE: 'Texture', CHARACTER: 'Character', CONCEPT_ART: 'Concept art', LAYOUT: 'Layout', OTHER: 'Other' },
  statuses: { DRAFT: 'Draft', IN_PROGRESS: 'In progress', NEEDS_REVIEW: 'Needs review', APPROVED: 'Approved', REJECTED: 'Rejected', ARCHIVED: 'Archived' },
  versionStatuses: { DRAFT: 'Draft', CANDIDATE: 'Candidate', NEEDS_REVIEW: 'Needs review', APPROVED: 'Approved', REJECTED: 'Rejected', SUPERSEDED: 'Superseded' },
  unknown: 'Unknown', loading: 'Loading assets…', loadingDetail: 'Loading asset detail…', more: 'Load more assets', retry: 'Try again', requestId: 'Request ID', empty: 'No assets yet. Create an asset record to begin.', noResults: 'No assets match these filters.', noPreview: 'No preview available', brokenPreview: 'Preview could not be loaded', inspect: 'Inspect asset', back: 'Back to asset library', noDescription: 'No description recorded.', noVersion: 'No versions yet', latest: 'Latest version', versionCount: 'Versions', history: 'Version history', historyNote: 'Version summaries are shown newest first. Inspect and compare exact versions below. Approval decisions are a later feature.', noDecisions: 'No decisions recorded for this asset.', decisions: 'Recent asset decisions', linkedReferences: 'Linked references', noReferences: 'No asset-level reference links recorded.', unavailable: 'Reference unavailable', rights: 'Usage rights / permission notes', noRights: 'No usage rights recorded. Confirm permission before reuse.', createdBy: 'Created by', updated: 'Last updated', readOnly: 'Your role can inspect assets but cannot change them.',
  required: 'Enter an asset title and choose a known asset type.', validation: 'Check the asset fields.', saved: 'Asset saved.', metadataSaved: 'Asset metadata updated.', archive: 'Archive asset', archiveConfirm: 'Archive this asset? Its versions and reference links remain preserved.', restore: 'Restore as draft', restoreNote: 'Restoring sets the logical asset to Draft. Version approval states remain unchanged.', preserveStatus: 'Keep current status', statusNote: 'Logical asset status changes leave version statuses unchanged. Approval requires a decision on a specific version.', conflict: 'The server has newer metadata. Load it for comparison; your draft remains in this form.', reload: 'Load latest metadata', latestMetadata: 'Latest server metadata', failedWrite: 'Check the asset before retrying a failed metadata change. Writes are never retried automatically.',
} as const
