import type { VersionView } from './api'
import type { VersionOptions } from './versionApi'
import { AssetMedia, AssetStatus } from './AssetMedia'
import { safeUrl, label } from '../references/display'
import { versionCopy as c } from './versionCopy'
export function VersionInspection({ version, options, inspect, prefix }: { version: VersionView; options: VersionOptions | null; inspect: (id: string) => void; prefix: string }) {
  const file = safeUrl(version.fileUrl ?? version.externalFileUrl)
  return <article className="version-inspection" aria-label={`${prefix}: Version ${version.versionNumber}`}><h5>{prefix}: Version {version.versionNumber}</h5><p><AssetStatus status={version.status} version /> · {version.isLatest ? c.latest : c.historical}</p><code>{version.id}</code>{version.isMetadataOnly ? <div className="asset-preview"><p>{c.metadataLabel}</p></div> : version.mimeType && !version.mimeType.startsWith('image/') ? <p>{c.unsupported}</p> : <AssetMedia key={version.thumbnailUrl ?? file} url={version.thumbnailUrl ?? file} title={`${version.assetTitle} version ${version.versionNumber}`} />}{file && <a href={file} target="_blank" rel="noopener noreferrer">{c.openFile}</a>}
    <dl className="asset-metadata"><dt>{c.rationale}</dt><dd>{version.revisionRationale}</dd><dt>{c.direction}</dt><dd>{options?.directions.find(value => value.id === version.directionRevisionId)?.label ?? version.directionRevisionId ?? c.none}</dd><dt>{c.brief}</dt><dd>{options?.briefs.find(value => value.id === version.briefRevisionId)?.label ?? version.briefRevisionId ?? c.none}</dd><dt>{c.prompt}</dt><dd>{version.prompt ?? c.unknown}</dd><dt>{c.negativePrompt}</dt><dd>{version.negativePrompt ?? c.unknown}</dd><dt>{c.provider}</dt><dd>{version.providerName ?? c.unknown}</dd><dt>{c.model}</dt><dd>{version.modelName ?? c.unknown}</dd><dt>{c.modelVersion}</dt><dd>{version.modelVersion ?? c.unknown}</dd><dt>Created by</dt><dd>{version.createdBy.displayName}</dd><dt>Created at</dt><dd><time dateTime={version.createdAt}>{new Date(version.createdAt).toLocaleString()}</time></dd><dt>Content checksum</dt><dd>{version.contentChecksum ?? c.unknown}</dd><dt>{c.mime}</dt><dd>{version.mimeType ?? c.unknown}</dd><dt>{c.width} / {c.height}</dt><dd>{version.width ?? c.unknown} / {version.height ?? c.unknown}</dd></dl>
    <h6>{c.attributes}</h6><dl className="asset-metadata">{Object.entries(c.categories).map(([key, name]) => <div className="version-attribute" key={key}><dt>{name}</dt><dd>{version.recordedAttributes[key as keyof typeof c.categories].join(' · ') || c.unknown}</dd></div>)}</dl><h6>{c.settings}</h6>{Object.entries(version.generationSettings).length ? <dl className="asset-metadata">{Object.entries(version.generationSettings).map(([key, value]) => <div className="version-attribute" key={key}><dt>{key}</dt><dd>{typeof value === 'object' ? JSON.stringify(value) : String(value)}</dd></div>)}</dl> : <p>{c.unknown}</p>}
    <h6>{c.lineage}</h6>{version.lineage.derivedFrom ? <p>{c.parent}: <button onClick={() => inspect(version.lineage.derivedFrom!.id)}>Version {version.lineage.derivedFrom.versionNumber}</button></p> : <p>{c.root}</p>}<p>{c.children}</p>{version.lineage.derivedVersions.length ? <ul>{version.lineage.derivedVersions.map(value => <li key={value.id}><button onClick={() => inspect(value.id)}>Version {value.versionNumber}</button> <AssetStatus status={value.status} version /></li>)}</ul> : <p>{c.noChildren}</p>}
    <h6>{c.pins}</h6><p className="note">{c.pinNote}</p>{version.pinnedIn.length ? <ul>{version.pinnedIn.map(pin => <li key={pin.collectionRevisionId}>{pin.collectionName} · Revision {pin.revisionNumber} · {label({ APPROVED: 'Approved', DRAFT: 'Draft', IN_REVIEW: 'In review', REJECTED: 'Rejected', SUPERSEDED: 'Superseded' }, pin.revisionStatus)}<p><code>{pin.collectionRevisionId}</code></p></li>)}</ul> : <p>{c.noPins}</p>}
    <h6>{c.references}</h6>{version.references.length ? <ul>{version.references.map(reference => { const record = options?.references.find(value => value.id === reference.referenceId); return <li key={reference.referenceId}><strong>{record?.title ?? reference.referenceId}</strong><p>{reference.usageNote}</p><p className="asset-rights">{record ? record.usageRightsNote ?? 'No usage rights recorded. Confirm permission before reuse.' : options ? 'Reference metadata unavailable.' : 'Loading reference metadata…'}</p></li> })}</ul> : <p>No version references recorded.</p>}
  </article>
}
