import { useEffect, useRef, useState } from 'react'
import { AssetVersionInputSchema, type AssetVersionInput } from '../../../packages/contracts/src'
import { ApiClientError, createIntentKey } from '../../lib/api/client'
import { isVersionFileUrl } from '../../lib/versionFile'
import type { AssetDetailView, VersionView } from './api'
import type { VersionOptions } from './versionApi'
import { versionCopy as c } from './versionCopy'
type Setting = { key: string; type: 'string' | 'number' | 'boolean' | 'null' | 'structured'; text: string; original?: unknown; id: string }
export function VersionForm({ asset, source, options, upload, save, cancel }: { asset: AssetDetailView; source?: VersionView; options: VersionOptions; upload?: (file: File) => Promise<{ data: { id: string; url: string } }>; save: (input: AssetVersionInput, key: string) => Promise<void>; cancel: () => void }) {
  const [fields, setFields] = useState({ revisionRationale: '', derivedFromVersionId: source?.id ?? '', directionRevisionId: '', briefRevisionId: '', externalFileUrl: '', mimeType: '', width: '', height: '', prompt: source?.prompt ?? '', negativePrompt: source?.negativePrompt ?? '', providerName: source?.providerName ?? '', modelName: source?.modelName ?? '', modelVersion: source?.modelVersion ?? '' })
  const [fileMode, setFileMode] = useState<'metadata' | 'upload' | 'external'>('metadata'); const [status, setStatus] = useState('DRAFT')
  const [uploadedFile, setUploadedFile] = useState<File | null>(null); const [uploading, setUploading] = useState(false); const [storageObjectId, setStorageObjectId] = useState<string | null>(null); const [previewUrl, setPreviewUrl] = useState<string | null>(null)
  const [attributes, setAttributes] = useState(Object.fromEntries(Object.keys(c.categories).map(key => [key, source?.recordedAttributes[key as keyof typeof c.categories].join('\n') ?? ''])))
  const [references, setReferences] = useState(source?.references ?? [])
  const [settings, setSettings] = useState<Setting[]>(() => Object.entries(source?.generationSettings ?? {}).map(([key, value]) => ({ id: crypto.randomUUID(), key, type: value === null ? 'null' : typeof value === 'number' ? 'number' : typeof value === 'boolean' ? 'boolean' : typeof value === 'string' ? 'string' : 'structured', text: typeof value === 'object' ? '' : String(value), original: value })))
  const [errors, setErrors] = useState<Record<string, string>>({}); const [error, setError] = useState<ApiClientError | null>(null); const [saving, setSaving] = useState(false); const busy = useRef(false); const intent = useRef<{ body: string; key: string } | null>(null); const form = useRef<HTMLFormElement>(null); const summary = useRef<HTMLDivElement>(null)
  useEffect(() => { form.current?.querySelector<HTMLElement>('textarea')?.focus() }, [])
  async function submit(event: React.FormEvent) {
    event.preventDefault(); if (busy.current) return
    const issues: Record<string, string> = {}; const generationSettings: Record<string, unknown> = Object.create(null)
    if (fileMode === 'external' && !isVersionFileUrl(fields.externalFileUrl)) issues.externalFileUrl = c.invalidUrl
    if (fileMode === 'upload' && !storageObjectId && !uploadedFile) issues.upload = 'Select an image file to upload.'
    for (const key of ['width', 'height'] as const) if (fileMode === 'external' && fields[key] && (!Number.isInteger(Number(fields[key])) || Number(fields[key]) <= 0)) issues[key] = c.invalidDimension
    settings.forEach((item, index) => { if (!item.key.trim() || Object.hasOwn(generationSettings, item.key.trim())) { issues[`settings.${index}`] = 'Use a unique, non-empty setting name.'; return } if (item.type === 'number' && (!item.text.trim() || !Number.isFinite(Number(item.text)))) { issues[`settings.${index}`] = 'Enter a finite numeric setting.'; return } if (item.type === 'boolean' && !['true', 'false'].includes(item.text)) { issues[`settings.${index}`] = 'Use true or false.'; return } generationSettings[item.key.trim()] = item.type === 'structured' ? item.original : item.type === 'number' ? Number(item.text) : item.type === 'boolean' ? item.text === 'true' : item.type === 'null' ? null : item.text })
    const association = (value: string) => value === 'none' ? null : value || undefined
    const parsed = AssetVersionInputSchema.safeParse({ revisionRationale: fields.revisionRationale.trim(), derivedFromVersionId: fields.derivedFromVersionId || null, directionRevisionId: association(fields.directionRevisionId), briefRevisionId: association(fields.briefRevisionId), metadataOnly: fileMode === 'metadata', storageObjectId: fileMode === 'upload' ? storageObjectId : null, externalFileUrl: fileMode === 'external' ? fields.externalFileUrl.trim() : null, mimeType: fileMode === 'external' ? fields.mimeType.trim() || null : uploadedFile?.type || null, width: fileMode === 'external' && fields.width ? Number(fields.width) : null, height: fileMode === 'external' && fields.height ? Number(fields.height) : null, prompt: fields.prompt || null, negativePrompt: fields.negativePrompt || null, providerName: fields.providerName.trim() || null, modelName: fields.modelName.trim() || null, modelVersion: fields.modelVersion.trim() || null, generationSettings, recordedAttributes: Object.fromEntries(Object.entries(attributes).map(([key, value]) => [key, value.split('\n').map(value => value.trim()).filter(Boolean)])), status, references })
    if (!parsed.success) for (const issue of parsed.error.issues) issues[issue.path.join('.')] ??= issue.message
    if (Object.keys(issues).length || !parsed.success) { setErrors(issues); queueMicrotask(() => summary.current?.focus()); return }
    const body = JSON.stringify(parsed.data); if (intent.current?.body !== body) intent.current = { body, key: createIntentKey() }
    busy.current = true; setSaving(true); setErrors({}); setError(null)
    try { await save(parsed.data, intent.current.key) } catch (value) { const failure = value instanceof ApiClientError ? value : new ApiClientError('Unable to save version.', { code: 'UNKNOWN' }); setError(failure); setErrors(Object.fromEntries(failure.details.map(item => [item.path.replace(/^body\./, ''), item.message]))); queueMicrotask(() => summary.current?.focus()) } finally { busy.current = false; setSaving(false) }
  }
  function field(key: keyof typeof fields, label: string, multiline = false, isRequired = false) { const props = { id: `version-${key}`, value: fields[key], onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setFields(previous => ({ ...previous, [key]: event.target.value })), 'aria-invalid': Boolean(errors[key]), 'aria-describedby': `version-error-${key}` }; return <div key={key}><label htmlFor={props.id}>{label}{isRequired && <span className="required-star"> *</span>}</label>{multiline ? <textarea {...props} /> : <input {...props} />}<p id={`version-error-${key}`} className="field-error">{errors[key]}</p></div> }
  return <form ref={form} className="asset-form version-form" aria-label={c.create} onSubmit={submit} noValidate><h4>{c.create}</h4><p>{c.immutable}</p>{(error || Object.keys(errors).length > 0) && <div ref={summary} tabIndex={-1} role="alert" className="project-error"><p>{error?.message ?? c.required}</p>{Object.entries(errors).map(([key, message]) => <p key={key}>{key}: {message}</p>)}{error?.requestId && <p>{c.requestId}: {error.requestId}</p>}{error && <p>{c.failedWrite}</p>}</div>}
    <fieldset disabled={saving}><legend className="sr-only">{c.create}</legend>{field('revisionRationale', c.rationale, true, true)}<p>{c.rationaleHelp}</p><label>{c.source}<select value={fields.derivedFromVersionId} onChange={event => setFields(previous => ({ ...previous, derivedFromVersionId: event.target.value }))}><option value="">{c.independent}</option>{asset.versions.map(version => <option key={version.id} value={version.id}>Version {version.versionNumber} · {version.id}</option>)}</select></label>
      {(['directionRevisionId', 'briefRevisionId'] as const).map(key => <label key={key}>{key === 'directionRevisionId' ? c.direction : c.brief}<select value={fields[key]} onChange={event => setFields(previous => ({ ...previous, [key]: event.target.value }))}><option value="">{key === 'directionRevisionId' ? c.defaultDirection : c.defaultBrief}</option><option value="none">{c.none}</option>{(key === 'directionRevisionId' ? options.directions : options.briefs).map(value => <option key={value.id} value={value.id}>{value.label}</option>)}</select></label>)}
      <label>{c.status}<select value={status} onChange={event => setStatus(event.target.value)}><option value="DRAFT">Draft</option><option value="CANDIDATE">Candidate</option><option value="NEEDS_REVIEW">Needs review</option></select></label><label>{c.fileMode}<select value={fileMode} onChange={event => setFileMode(event.target.value as 'metadata' | 'upload' | 'external')}><option value="metadata">{c.metadataOnly}</option><option value="upload">{c.uploadImage}</option><option value="external">{c.external}</option></select></label><p className="note">{c.fileNote}</p>
      {fileMode === 'upload' && <div className="version-upload-section"><label htmlFor="version-file-upload">Image File <span className="required-star">*</span></label><input id="version-file-upload" type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={async event => { const file = event.target.files?.[0]; if (!file) return; setUploadedFile(file); setPreviewUrl(URL.createObjectURL(file)); if (upload) { setUploading(true); setError(null); try { const res = await upload(file); setStorageObjectId(res.data.id) } catch (err) { setError(err instanceof ApiClientError ? err : new ApiClientError('Upload failed.', { code: 'UPLOAD_FAILED' })) } finally { setUploading(false) } } }} />{uploading && <p className="note">Uploading image to server...</p>}{previewUrl && <div style={{ marginTop: '0.5rem', marginBottom: '1rem' }}><p className="note">Preview:</p><img src={previewUrl} alt="Preview" style={{ maxWidth: '240px', maxHeight: '160px', borderRadius: '8px', objectFit: 'cover', border: '1px solid var(--border)' }} /></div>}{errors.upload && <p className="field-error">{errors.upload}</p>}</div>}
      {fileMode === 'external' && <>{field('externalFileUrl', c.fileUrl, false, true)}{field('mimeType', c.mime)}<div className="version-pair">{field('width', c.width)}{field('height', c.height)}</div></>}
      {field('prompt', c.prompt, true)}{field('negativePrompt', c.negativePrompt, true)}{field('providerName', c.provider)}{field('modelName', c.model)}{field('modelVersion', c.modelVersion)}
      <h5>{c.attributes}</h5><p className="note">{c.tokens}</p><div className="version-pair">{Object.entries(c.categories).map(([key, label]) => <label key={key}>{label}<textarea value={attributes[key]} onChange={event => setAttributes(previous => ({ ...previous, [key]: event.target.value }))} /></label>)}</div>
      <h5>{c.settings}</h5>{settings.map((item, index) => <div className="version-setting" key={item.id}><label>{c.settingKey}<input value={item.key} onChange={event => setSettings(previous => previous.map(value => value.id === item.id ? { ...value, key: event.target.value } : value))} /></label><label>{c.settingType}<select value={item.type} disabled={item.type === 'structured'} onChange={event => { const type = event.target.value; if (type === 'string' || type === 'number' || type === 'boolean' || type === 'null') setSettings(previous => previous.map(value => value.id === item.id ? { ...value, type, text: type === 'boolean' ? 'false' : '' } : value)) }}><option value="string">Text</option><option value="number">Number</option><option value="boolean">Boolean</option><option value="null">Not recorded</option>{item.type === 'structured' && <option value="structured">Structured</option>}</select></label>{item.type === 'structured' ? <p>{c.nested}</p> : item.type !== 'null' && <label>{c.settingValue}<input value={item.text} onChange={event => setSettings(previous => previous.map(value => value.id === item.id ? { ...value, text: event.target.value } : value))} /></label>}<button type="button" onClick={() => setSettings(previous => previous.filter(value => value.id !== item.id))}>{c.remove}</button><p>{errors[`settings.${index}`]}</p></div>)}<button type="button" onClick={() => setSettings(previous => [...previous, { id: crypto.randomUUID(), key: '', type: 'string', text: '' }])}>{c.addSetting}</button>
      <h5>{c.references}</h5>{options.references.map(reference => { const selected = references.find(value => value.referenceId === reference.id); return <div key={reference.id}><label className="asset-checkbox"><input type="checkbox" checked={Boolean(selected)} onChange={event => setReferences(previous => event.target.checked ? [...previous, { referenceId: reference.id, usageNote: null }] : previous.filter(value => value.referenceId !== reference.id))} />{reference.title}</label><p className="asset-rights">{reference.usageRightsNote ?? 'No usage rights recorded. Confirm permission before reuse.'}</p>{selected && <label>{c.note}: {reference.title}<textarea value={selected.usageNote ?? ''} onChange={event => setReferences(previous => previous.map(value => value.referenceId === reference.id ? { ...value, usageNote: event.target.value || null } : value))} /></label>}</div>})}
      <div className="project-actions"><button>{saving ? c.saving : c.save}</button><button type="button" onClick={cancel}>{c.cancel}</button></div>
    </fieldset>
  </form>
}
